/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type AssetAmountStruct = { asset: AddressLike; amount: BigNumberish };

export type AssetAmountStructOutput = [asset: string, amount: bigint] & {
  asset: string;
  amount: bigint;
};

export type AccountSnapshotStruct = {
  account: AddressLike;
  shares: BigNumberish;
  grossClaimValue: BigNumberish;
  accountingClaimValue: BigNumberish;
  activeClaims: AssetAmountStruct[];
};

export type AccountSnapshotStructOutput = [
  account: string,
  shares: bigint,
  grossClaimValue: bigint,
  accountingClaimValue: bigint,
  activeClaims: AssetAmountStructOutput[]
] & {
  account: string;
  shares: bigint;
  grossClaimValue: bigint;
  accountingClaimValue: bigint;
  activeClaims: AssetAmountStructOutput[];
};

export type ComponentValueStruct = {
  asset: AddressLike;
  balance: BigNumberish;
  price: BigNumberish;
  value: BigNumberish;
  weightBps: BigNumberish;
  status: BigNumberish;
};

export type ComponentValueStructOutput = [
  asset: string,
  balance: bigint,
  price: bigint,
  value: bigint,
  weightBps: bigint,
  status: bigint
] & {
  asset: string;
  balance: bigint;
  price: bigint;
  value: bigint;
  weightBps: bigint;
  status: bigint;
};

export type SubstitutionPlanStruct = {
  nonce: BigNumberish;
  state: BigNumberish;
  outgoing: AddressLike;
  incoming: AddressLike;
  outgoingWeightBps: BigNumberish;
  incomingWeightBps: BigNumberish;
  announcedAt: BigNumberish;
  executableAt: BigNumberish;
  expiresAt: BigNumberish;
  outgoingBalanceSnapshot: BigNumberish;
  incomingRequiredValue: BigNumberish;
  incomingReceived: BigNumberish;
  memoHash: BytesLike;
};

export type SubstitutionPlanStructOutput = [
  nonce: bigint,
  state: bigint,
  outgoing: string,
  incoming: string,
  outgoingWeightBps: bigint,
  incomingWeightBps: bigint,
  announcedAt: bigint,
  executableAt: bigint,
  expiresAt: bigint,
  outgoingBalanceSnapshot: bigint,
  incomingRequiredValue: bigint,
  incomingReceived: bigint,
  memoHash: string
] & {
  nonce: bigint;
  state: bigint;
  outgoing: string;
  incoming: string;
  outgoingWeightBps: bigint;
  incomingWeightBps: bigint;
  announcedAt: bigint;
  executableAt: bigint;
  expiresAt: bigint;
  outgoingBalanceSnapshot: bigint;
  incomingRequiredValue: bigint;
  incomingReceived: bigint;
  memoHash: string;
};

export type WeightUpdateStruct = {
  nonce: BigNumberish;
  state: BigNumberish;
  announcedAt: BigNumberish;
  executableAt: BigNumberish;
  expiresAt: BigNumberish;
  componentHash: BytesLike;
  memoHash: BytesLike;
};

export type WeightUpdateStructOutput = [
  nonce: bigint,
  state: bigint,
  announcedAt: bigint,
  executableAt: bigint,
  expiresAt: bigint,
  componentHash: string,
  memoHash: string
] & {
  nonce: bigint;
  state: bigint;
  announcedAt: bigint;
  executableAt: bigint;
  expiresAt: bigint;
  componentHash: string;
  memoHash: string;
};

export type HarvestReportStruct = {
  asset: AddressLike;
  source: AddressLike;
  grossAmount: BigNumberish;
  feeAmount: BigNumberish;
  netAmount: BigNumberish;
  reportHash: BytesLike;
  timestamp: BigNumberish;
};

export type HarvestReportStructOutput = [
  asset: string,
  source: string,
  grossAmount: bigint,
  feeAmount: bigint,
  netAmount: bigint,
  reportHash: string,
  timestamp: bigint
] & {
  asset: string;
  source: string;
  grossAmount: bigint;
  feeAmount: bigint;
  netAmount: bigint;
  reportHash: string;
  timestamp: bigint;
};

export type NavReportStruct = {
  totalSupply: BigNumberish;
  grossValue: BigNumberish;
  accountingValue: BigNumberish;
  backedSupply: BigNumberish;
  navPerShare: BigNumberish;
  accountingNavPerShare: BigNumberish;
  transitionWindow: boolean;
};

export type NavReportStructOutput = [
  totalSupply: bigint,
  grossValue: bigint,
  accountingValue: bigint,
  backedSupply: bigint,
  navPerShare: bigint,
  accountingNavPerShare: bigint,
  transitionWindow: boolean
] & {
  totalSupply: bigint;
  grossValue: bigint;
  accountingValue: bigint;
  backedSupply: bigint;
  navPerShare: bigint;
  accountingNavPerShare: bigint;
  transitionWindow: boolean;
};

export type RedeemQuoteStruct = {
  shares: BigNumberish;
  supplyBasis: BigNumberish;
  selectedLane: boolean;
  transitionWindow: boolean;
  outputs: AssetAmountStruct[];
};

export type RedeemQuoteStructOutput = [
  shares: bigint,
  supplyBasis: bigint,
  selectedLane: boolean,
  transitionWindow: boolean,
  outputs: AssetAmountStructOutput[]
] & {
  shares: bigint;
  supplyBasis: bigint;
  selectedLane: boolean;
  transitionWindow: boolean;
  outputs: AssetAmountStructOutput[];
};

export type MintQuoteStruct = {
  basketAmount: BigNumberish;
  grossValue: BigNumberish;
  deposits: AssetAmountStruct[];
};

export type MintQuoteStructOutput = [
  basketAmount: bigint,
  grossValue: bigint,
  deposits: AssetAmountStructOutput[]
] & {
  basketAmount: bigint;
  grossValue: bigint;
  deposits: AssetAmountStructOutput[];
};

export interface ReverieBasketProtocolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS"
      | "DEFAULT_ADMIN_ROLE"
      | "GOVERNOR_ROLE"
      | "GUARDIAN_ROLE"
      | "KEEPER_ROLE"
      | "PAUSER_ROLE"
      | "REBALANCER_ROLE"
      | "RISK_MANAGER_ROLE"
      | "STRATEGIST_ROLE"
      | "WAD"
      | "accountSnapshot"
      | "accountingBasketValue"
      | "accountingNavPerShare"
      | "announceSubstitution"
      | "announceWeightUpdate"
      | "applyWeightUpdate"
      | "backedSupply"
      | "basketToken"
      | "cancelSubstitution"
      | "cancelWeightUpdate"
      | "completeSubstitution"
      | "componentValue"
      | "componentValues"
      | "currentSubstitution"
      | "currentWeightUpdate"
      | "grantRole"
      | "grossBasketValue"
      | "harvest"
      | "harvestedFees"
      | "harvestedGross"
      | "hasRole"
      | "lastHarvest"
      | "lastSubstitution"
      | "mint"
      | "navPerShare"
      | "navReport"
      | "oracle"
      | "pause"
      | "paused"
      | "pendingWeightAssets"
      | "previewInKindRedeem"
      | "previewMint"
      | "previewRedeem"
      | "receiveSubstitutionInventory"
      | "redeem"
      | "redeemInKind"
      | "registry"
      | "renounceRole"
      | "revokeRole"
      | "riskPolicy"
      | "setTreasury"
      | "sweepRetiredAsset"
      | "token"
      | "treasury"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Harvested"
      | "InKindRedeemed"
      | "Minted"
      | "ProtocolPaused"
      | "ProtocolUnpaused"
      | "Redeemed"
      | "RetiredAssetSwept"
      | "RoleGranted"
      | "RoleRevoked"
      | "SubstitutionAnnounced"
      | "SubstitutionCancelled"
      | "SubstitutionCompleted"
      | "SubstitutionInventoryReceived"
      | "TreasuryUpdated"
      | "WeightUpdateAnnounced"
      | "WeightUpdateApplied"
      | "WeightUpdateCancelled"
  ): EventFragment;

  encodeFunctionData(functionFragment: "BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GUARDIAN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEEPER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REBALANCER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RISK_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STRATEGIST_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "WAD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "accountSnapshot",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "accountingBasketValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accountingNavPerShare",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "announceSubstitution",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "announceWeightUpdate",
    values: [
      AddressLike[],
      BigNumberish[],
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "applyWeightUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "backedSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "basketToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSubstitution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelWeightUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "completeSubstitution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "componentValue",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "componentValues",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "currentSubstitution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentWeightUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grossBasketValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "harvest",
    values: [AddressLike, BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "harvestedFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "harvestedGross",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastHarvest",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastSubstitution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "navPerShare",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "navReport", values?: undefined): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingWeightAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "previewInKindRedeem",
    values: [BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "previewMint",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "previewRedeem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveSubstitutionInventory",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemInKind",
    values: [BigNumberish, AddressLike[], AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "riskPolicy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sweepRetiredAsset",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(functionFragment: "BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GUARDIAN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KEEPER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REBALANCER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RISK_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STRATEGIST_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "WAD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "accountSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accountingBasketValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accountingNavPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "announceSubstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "announceWeightUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyWeightUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "backedSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "basketToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelSubstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelWeightUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeSubstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "componentValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "componentValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentSubstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentWeightUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grossBasketValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "harvest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "harvestedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "harvestedGross",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastHarvest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastSubstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "navPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "navReport", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingWeightAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewInKindRedeem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewRedeem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveSubstitutionInventory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "redeemInKind",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "riskPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sweepRetiredAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace HarvestedEvent {
  export type InputTuple = [
    asset: AddressLike,
    source: AddressLike,
    grossAmount: BigNumberish,
    feeAmount: BigNumberish,
    netAmount: BigNumberish,
    reportHash: BytesLike
  ];
  export type OutputTuple = [
    asset: string,
    source: string,
    grossAmount: bigint,
    feeAmount: bigint,
    netAmount: bigint,
    reportHash: string
  ];
  export interface OutputObject {
    asset: string;
    source: string;
    grossAmount: bigint;
    feeAmount: bigint;
    netAmount: bigint;
    reportHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InKindRedeemedEvent {
  export type InputTuple = [
    caller: AddressLike,
    receiver: AddressLike,
    shares: BigNumberish,
    supplyBasis: BigNumberish,
    components: BigNumberish
  ];
  export type OutputTuple = [
    caller: string,
    receiver: string,
    shares: bigint,
    supplyBasis: bigint,
    components: bigint
  ];
  export interface OutputObject {
    caller: string;
    receiver: string;
    shares: bigint;
    supplyBasis: bigint;
    components: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintedEvent {
  export type InputTuple = [
    caller: AddressLike,
    receiver: AddressLike,
    shares: BigNumberish,
    components: BigNumberish
  ];
  export type OutputTuple = [
    caller: string,
    receiver: string,
    shares: bigint,
    components: bigint
  ];
  export interface OutputObject {
    caller: string;
    receiver: string;
    shares: bigint;
    components: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolPausedEvent {
  export type InputTuple = [caller: AddressLike];
  export type OutputTuple = [caller: string];
  export interface OutputObject {
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolUnpausedEvent {
  export type InputTuple = [caller: AddressLike];
  export type OutputTuple = [caller: string];
  export interface OutputObject {
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemedEvent {
  export type InputTuple = [
    caller: AddressLike,
    receiver: AddressLike,
    shares: BigNumberish,
    components: BigNumberish
  ];
  export type OutputTuple = [
    caller: string,
    receiver: string,
    shares: bigint,
    components: bigint
  ];
  export interface OutputObject {
    caller: string;
    receiver: string;
    shares: bigint;
    components: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RetiredAssetSweptEvent {
  export type InputTuple = [
    asset: AddressLike,
    receiver: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [asset: string, receiver: string, amount: bigint];
  export interface OutputObject {
    asset: string;
    receiver: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubstitutionAnnouncedEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    outgoing: AddressLike,
    incoming: AddressLike,
    incomingWeightBps: BigNumberish,
    executableAt: BigNumberish,
    expiresAt: BigNumberish,
    memoHash: BytesLike
  ];
  export type OutputTuple = [
    nonce: bigint,
    outgoing: string,
    incoming: string,
    incomingWeightBps: bigint,
    executableAt: bigint,
    expiresAt: bigint,
    memoHash: string
  ];
  export interface OutputObject {
    nonce: bigint;
    outgoing: string;
    incoming: string;
    incomingWeightBps: bigint;
    executableAt: bigint;
    expiresAt: bigint;
    memoHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubstitutionCancelledEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    outgoing: AddressLike,
    incoming: AddressLike
  ];
  export type OutputTuple = [nonce: bigint, outgoing: string, incoming: string];
  export interface OutputObject {
    nonce: bigint;
    outgoing: string;
    incoming: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubstitutionCompletedEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    outgoing: AddressLike,
    incoming: AddressLike
  ];
  export type OutputTuple = [nonce: bigint, outgoing: string, incoming: string];
  export interface OutputObject {
    nonce: bigint;
    outgoing: string;
    incoming: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubstitutionInventoryReceivedEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    incoming: AddressLike,
    source: AddressLike,
    amount: BigNumberish,
    value: BigNumberish
  ];
  export type OutputTuple = [
    nonce: bigint,
    incoming: string,
    source: string,
    amount: bigint,
    value: bigint
  ];
  export interface OutputObject {
    nonce: bigint;
    incoming: string;
    source: string;
    amount: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WeightUpdateAnnouncedEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    executableAt: BigNumberish,
    expiresAt: BigNumberish,
    componentHash: BytesLike,
    memoHash: BytesLike
  ];
  export type OutputTuple = [
    nonce: bigint,
    executableAt: bigint,
    expiresAt: bigint,
    componentHash: string,
    memoHash: string
  ];
  export interface OutputObject {
    nonce: bigint;
    executableAt: bigint;
    expiresAt: bigint;
    componentHash: string;
    memoHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WeightUpdateAppliedEvent {
  export type InputTuple = [nonce: BigNumberish, componentHash: BytesLike];
  export type OutputTuple = [nonce: bigint, componentHash: string];
  export interface OutputObject {
    nonce: bigint;
    componentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WeightUpdateCancelledEvent {
  export type InputTuple = [nonce: BigNumberish];
  export type OutputTuple = [nonce: bigint];
  export interface OutputObject {
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReverieBasketProtocol extends BaseContract {
  connect(runner?: ContractRunner | null): ReverieBasketProtocol;
  waitForDeployment(): Promise<this>;

  interface: ReverieBasketProtocolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GOVERNOR_ROLE: TypedContractMethod<[], [string], "view">;

  GUARDIAN_ROLE: TypedContractMethod<[], [string], "view">;

  KEEPER_ROLE: TypedContractMethod<[], [string], "view">;

  PAUSER_ROLE: TypedContractMethod<[], [string], "view">;

  REBALANCER_ROLE: TypedContractMethod<[], [string], "view">;

  RISK_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  STRATEGIST_ROLE: TypedContractMethod<[], [string], "view">;

  WAD: TypedContractMethod<[], [bigint], "view">;

  accountSnapshot: TypedContractMethod<
    [account: AddressLike],
    [AccountSnapshotStructOutput],
    "view"
  >;

  accountingBasketValue: TypedContractMethod<[], [bigint], "view">;

  accountingNavPerShare: TypedContractMethod<[], [bigint], "view">;

  announceSubstitution: TypedContractMethod<
    [
      outgoing: AddressLike,
      incoming: AddressLike,
      delaySeconds: BigNumberish,
      ttlSeconds: BigNumberish,
      memoHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  announceWeightUpdate: TypedContractMethod<
    [
      assets: AddressLike[],
      targetWeights: BigNumberish[],
      delaySeconds: BigNumberish,
      ttlSeconds: BigNumberish,
      memoHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  applyWeightUpdate: TypedContractMethod<[], [void], "nonpayable">;

  backedSupply: TypedContractMethod<[], [bigint], "view">;

  basketToken: TypedContractMethod<[], [string], "view">;

  cancelSubstitution: TypedContractMethod<[], [void], "nonpayable">;

  cancelWeightUpdate: TypedContractMethod<[], [void], "nonpayable">;

  completeSubstitution: TypedContractMethod<[], [void], "nonpayable">;

  componentValue: TypedContractMethod<
    [asset: AddressLike],
    [ComponentValueStructOutput],
    "view"
  >;

  componentValues: TypedContractMethod<
    [assets: AddressLike[]],
    [ComponentValueStructOutput[]],
    "view"
  >;

  currentSubstitution: TypedContractMethod<
    [],
    [SubstitutionPlanStructOutput],
    "view"
  >;

  currentWeightUpdate: TypedContractMethod<
    [],
    [WeightUpdateStructOutput],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  grossBasketValue: TypedContractMethod<[], [bigint], "view">;

  harvest: TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      source: AddressLike,
      reportHash: BytesLike
    ],
    [HarvestReportStructOutput],
    "nonpayable"
  >;

  harvestedFees: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  harvestedGross: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  lastHarvest: TypedContractMethod<
    [asset: AddressLike],
    [HarvestReportStructOutput],
    "view"
  >;

  lastSubstitution: TypedContractMethod<
    [],
    [SubstitutionPlanStructOutput],
    "view"
  >;

  mint: TypedContractMethod<
    [basketAmount: BigNumberish, receiver: AddressLike],
    [bigint],
    "nonpayable"
  >;

  navPerShare: TypedContractMethod<[], [bigint], "view">;

  navReport: TypedContractMethod<[], [NavReportStructOutput], "view">;

  oracle: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingWeightAssets: TypedContractMethod<
    [],
    [[string[], bigint[]] & { assets: string[]; weights: bigint[] }],
    "view"
  >;

  previewInKindRedeem: TypedContractMethod<
    [shares: BigNumberish, requestedAssets: AddressLike[]],
    [RedeemQuoteStructOutput],
    "view"
  >;

  previewMint: TypedContractMethod<
    [basketAmount: BigNumberish],
    [MintQuoteStructOutput],
    "view"
  >;

  previewRedeem: TypedContractMethod<
    [shares: BigNumberish],
    [RedeemQuoteStructOutput],
    "view"
  >;

  receiveSubstitutionInventory: TypedContractMethod<
    [amount: BigNumberish, source: AddressLike],
    [void],
    "nonpayable"
  >;

  redeem: TypedContractMethod<
    [shares: BigNumberish, receiver: AddressLike],
    [AssetAmountStructOutput[]],
    "nonpayable"
  >;

  redeemInKind: TypedContractMethod<
    [
      shares: BigNumberish,
      requestedAssets: AddressLike[],
      receiver: AddressLike
    ],
    [AssetAmountStructOutput[]],
    "nonpayable"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<[role: BytesLike], [void], "nonpayable">;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  riskPolicy: TypedContractMethod<[], [string], "view">;

  setTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  sweepRetiredAsset: TypedContractMethod<
    [asset: AddressLike, receiver: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GOVERNOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GUARDIAN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEEPER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PAUSER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REBALANCER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RISK_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "STRATEGIST_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WAD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accountSnapshot"
  ): TypedContractMethod<
    [account: AddressLike],
    [AccountSnapshotStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "accountingBasketValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accountingNavPerShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "announceSubstitution"
  ): TypedContractMethod<
    [
      outgoing: AddressLike,
      incoming: AddressLike,
      delaySeconds: BigNumberish,
      ttlSeconds: BigNumberish,
      memoHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "announceWeightUpdate"
  ): TypedContractMethod<
    [
      assets: AddressLike[],
      targetWeights: BigNumberish[],
      delaySeconds: BigNumberish,
      ttlSeconds: BigNumberish,
      memoHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "applyWeightUpdate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "backedSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "basketToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelSubstitution"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelWeightUpdate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeSubstitution"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "componentValue"
  ): TypedContractMethod<
    [asset: AddressLike],
    [ComponentValueStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "componentValues"
  ): TypedContractMethod<
    [assets: AddressLike[]],
    [ComponentValueStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "currentSubstitution"
  ): TypedContractMethod<[], [SubstitutionPlanStructOutput], "view">;
  getFunction(
    nameOrSignature: "currentWeightUpdate"
  ): TypedContractMethod<[], [WeightUpdateStructOutput], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grossBasketValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "harvest"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      source: AddressLike,
      reportHash: BytesLike
    ],
    [HarvestReportStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "harvestedFees"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "harvestedGross"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastHarvest"
  ): TypedContractMethod<
    [asset: AddressLike],
    [HarvestReportStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastSubstitution"
  ): TypedContractMethod<[], [SubstitutionPlanStructOutput], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [basketAmount: BigNumberish, receiver: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "navPerShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "navReport"
  ): TypedContractMethod<[], [NavReportStructOutput], "view">;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingWeightAssets"
  ): TypedContractMethod<
    [],
    [[string[], bigint[]] & { assets: string[]; weights: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "previewInKindRedeem"
  ): TypedContractMethod<
    [shares: BigNumberish, requestedAssets: AddressLike[]],
    [RedeemQuoteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "previewMint"
  ): TypedContractMethod<
    [basketAmount: BigNumberish],
    [MintQuoteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "previewRedeem"
  ): TypedContractMethod<
    [shares: BigNumberish],
    [RedeemQuoteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "receiveSubstitutionInventory"
  ): TypedContractMethod<
    [amount: BigNumberish, source: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<
    [shares: BigNumberish, receiver: AddressLike],
    [AssetAmountStructOutput[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "redeemInKind"
  ): TypedContractMethod<
    [
      shares: BigNumberish,
      requestedAssets: AddressLike[],
      receiver: AddressLike
    ],
    [AssetAmountStructOutput[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<[role: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "riskPolicy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sweepRetiredAsset"
  ): TypedContractMethod<
    [asset: AddressLike, receiver: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Harvested"
  ): TypedContractEvent<
    HarvestedEvent.InputTuple,
    HarvestedEvent.OutputTuple,
    HarvestedEvent.OutputObject
  >;
  getEvent(
    key: "InKindRedeemed"
  ): TypedContractEvent<
    InKindRedeemedEvent.InputTuple,
    InKindRedeemedEvent.OutputTuple,
    InKindRedeemedEvent.OutputObject
  >;
  getEvent(
    key: "Minted"
  ): TypedContractEvent<
    MintedEvent.InputTuple,
    MintedEvent.OutputTuple,
    MintedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolPaused"
  ): TypedContractEvent<
    ProtocolPausedEvent.InputTuple,
    ProtocolPausedEvent.OutputTuple,
    ProtocolPausedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolUnpaused"
  ): TypedContractEvent<
    ProtocolUnpausedEvent.InputTuple,
    ProtocolUnpausedEvent.OutputTuple,
    ProtocolUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Redeemed"
  ): TypedContractEvent<
    RedeemedEvent.InputTuple,
    RedeemedEvent.OutputTuple,
    RedeemedEvent.OutputObject
  >;
  getEvent(
    key: "RetiredAssetSwept"
  ): TypedContractEvent<
    RetiredAssetSweptEvent.InputTuple,
    RetiredAssetSweptEvent.OutputTuple,
    RetiredAssetSweptEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SubstitutionAnnounced"
  ): TypedContractEvent<
    SubstitutionAnnouncedEvent.InputTuple,
    SubstitutionAnnouncedEvent.OutputTuple,
    SubstitutionAnnouncedEvent.OutputObject
  >;
  getEvent(
    key: "SubstitutionCancelled"
  ): TypedContractEvent<
    SubstitutionCancelledEvent.InputTuple,
    SubstitutionCancelledEvent.OutputTuple,
    SubstitutionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "SubstitutionCompleted"
  ): TypedContractEvent<
    SubstitutionCompletedEvent.InputTuple,
    SubstitutionCompletedEvent.OutputTuple,
    SubstitutionCompletedEvent.OutputObject
  >;
  getEvent(
    key: "SubstitutionInventoryReceived"
  ): TypedContractEvent<
    SubstitutionInventoryReceivedEvent.InputTuple,
    SubstitutionInventoryReceivedEvent.OutputTuple,
    SubstitutionInventoryReceivedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WeightUpdateAnnounced"
  ): TypedContractEvent<
    WeightUpdateAnnouncedEvent.InputTuple,
    WeightUpdateAnnouncedEvent.OutputTuple,
    WeightUpdateAnnouncedEvent.OutputObject
  >;
  getEvent(
    key: "WeightUpdateApplied"
  ): TypedContractEvent<
    WeightUpdateAppliedEvent.InputTuple,
    WeightUpdateAppliedEvent.OutputTuple,
    WeightUpdateAppliedEvent.OutputObject
  >;
  getEvent(
    key: "WeightUpdateCancelled"
  ): TypedContractEvent<
    WeightUpdateCancelledEvent.InputTuple,
    WeightUpdateCancelledEvent.OutputTuple,
    WeightUpdateCancelledEvent.OutputObject
  >;

  filters: {
    "Harvested(address,address,uint256,uint256,uint256,bytes32)": TypedContractEvent<
      HarvestedEvent.InputTuple,
      HarvestedEvent.OutputTuple,
      HarvestedEvent.OutputObject
    >;
    Harvested: TypedContractEvent<
      HarvestedEvent.InputTuple,
      HarvestedEvent.OutputTuple,
      HarvestedEvent.OutputObject
    >;

    "InKindRedeemed(address,address,uint256,uint256,uint256)": TypedContractEvent<
      InKindRedeemedEvent.InputTuple,
      InKindRedeemedEvent.OutputTuple,
      InKindRedeemedEvent.OutputObject
    >;
    InKindRedeemed: TypedContractEvent<
      InKindRedeemedEvent.InputTuple,
      InKindRedeemedEvent.OutputTuple,
      InKindRedeemedEvent.OutputObject
    >;

    "Minted(address,address,uint256,uint256)": TypedContractEvent<
      MintedEvent.InputTuple,
      MintedEvent.OutputTuple,
      MintedEvent.OutputObject
    >;
    Minted: TypedContractEvent<
      MintedEvent.InputTuple,
      MintedEvent.OutputTuple,
      MintedEvent.OutputObject
    >;

    "ProtocolPaused(address)": TypedContractEvent<
      ProtocolPausedEvent.InputTuple,
      ProtocolPausedEvent.OutputTuple,
      ProtocolPausedEvent.OutputObject
    >;
    ProtocolPaused: TypedContractEvent<
      ProtocolPausedEvent.InputTuple,
      ProtocolPausedEvent.OutputTuple,
      ProtocolPausedEvent.OutputObject
    >;

    "ProtocolUnpaused(address)": TypedContractEvent<
      ProtocolUnpausedEvent.InputTuple,
      ProtocolUnpausedEvent.OutputTuple,
      ProtocolUnpausedEvent.OutputObject
    >;
    ProtocolUnpaused: TypedContractEvent<
      ProtocolUnpausedEvent.InputTuple,
      ProtocolUnpausedEvent.OutputTuple,
      ProtocolUnpausedEvent.OutputObject
    >;

    "Redeemed(address,address,uint256,uint256)": TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;
    Redeemed: TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;

    "RetiredAssetSwept(address,address,uint256)": TypedContractEvent<
      RetiredAssetSweptEvent.InputTuple,
      RetiredAssetSweptEvent.OutputTuple,
      RetiredAssetSweptEvent.OutputObject
    >;
    RetiredAssetSwept: TypedContractEvent<
      RetiredAssetSweptEvent.InputTuple,
      RetiredAssetSweptEvent.OutputTuple,
      RetiredAssetSweptEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SubstitutionAnnounced(uint64,address,address,uint16,uint40,uint40,bytes32)": TypedContractEvent<
      SubstitutionAnnouncedEvent.InputTuple,
      SubstitutionAnnouncedEvent.OutputTuple,
      SubstitutionAnnouncedEvent.OutputObject
    >;
    SubstitutionAnnounced: TypedContractEvent<
      SubstitutionAnnouncedEvent.InputTuple,
      SubstitutionAnnouncedEvent.OutputTuple,
      SubstitutionAnnouncedEvent.OutputObject
    >;

    "SubstitutionCancelled(uint64,address,address)": TypedContractEvent<
      SubstitutionCancelledEvent.InputTuple,
      SubstitutionCancelledEvent.OutputTuple,
      SubstitutionCancelledEvent.OutputObject
    >;
    SubstitutionCancelled: TypedContractEvent<
      SubstitutionCancelledEvent.InputTuple,
      SubstitutionCancelledEvent.OutputTuple,
      SubstitutionCancelledEvent.OutputObject
    >;

    "SubstitutionCompleted(uint64,address,address)": TypedContractEvent<
      SubstitutionCompletedEvent.InputTuple,
      SubstitutionCompletedEvent.OutputTuple,
      SubstitutionCompletedEvent.OutputObject
    >;
    SubstitutionCompleted: TypedContractEvent<
      SubstitutionCompletedEvent.InputTuple,
      SubstitutionCompletedEvent.OutputTuple,
      SubstitutionCompletedEvent.OutputObject
    >;

    "SubstitutionInventoryReceived(uint64,address,address,uint256,uint256)": TypedContractEvent<
      SubstitutionInventoryReceivedEvent.InputTuple,
      SubstitutionInventoryReceivedEvent.OutputTuple,
      SubstitutionInventoryReceivedEvent.OutputObject
    >;
    SubstitutionInventoryReceived: TypedContractEvent<
      SubstitutionInventoryReceivedEvent.InputTuple,
      SubstitutionInventoryReceivedEvent.OutputTuple,
      SubstitutionInventoryReceivedEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "WeightUpdateAnnounced(uint64,uint40,uint40,bytes32,bytes32)": TypedContractEvent<
      WeightUpdateAnnouncedEvent.InputTuple,
      WeightUpdateAnnouncedEvent.OutputTuple,
      WeightUpdateAnnouncedEvent.OutputObject
    >;
    WeightUpdateAnnounced: TypedContractEvent<
      WeightUpdateAnnouncedEvent.InputTuple,
      WeightUpdateAnnouncedEvent.OutputTuple,
      WeightUpdateAnnouncedEvent.OutputObject
    >;

    "WeightUpdateApplied(uint64,bytes32)": TypedContractEvent<
      WeightUpdateAppliedEvent.InputTuple,
      WeightUpdateAppliedEvent.OutputTuple,
      WeightUpdateAppliedEvent.OutputObject
    >;
    WeightUpdateApplied: TypedContractEvent<
      WeightUpdateAppliedEvent.InputTuple,
      WeightUpdateAppliedEvent.OutputTuple,
      WeightUpdateAppliedEvent.OutputObject
    >;

    "WeightUpdateCancelled(uint64)": TypedContractEvent<
      WeightUpdateCancelledEvent.InputTuple,
      WeightUpdateCancelledEvent.OutputTuple,
      WeightUpdateCancelledEvent.OutputObject
    >;
    WeightUpdateCancelled: TypedContractEvent<
      WeightUpdateCancelledEvent.InputTuple,
      WeightUpdateCancelledEvent.OutputTuple,
      WeightUpdateCancelledEvent.OutputObject
    >;
  };
}
