/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IComponentRegistry,
  IComponentRegistryInterface,
} from "../../interfaces/IComponentRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "decimals",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "weightBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "maxDriftBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "harvestFeeBps",
        type: "uint16",
      },
    ],
    name: "ComponentListed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "redeemable",
        type: "bool",
      },
    ],
    name: "ComponentRedeemableUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "maxDriftBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "harvestFeeBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint96",
        name: "maxBalance",
        type: "uint96",
      },
    ],
    name: "ComponentRiskUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "oldStatus",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "newStatus",
        type: "uint8",
      },
    ],
    name: "ComponentStatusUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "oldTargetBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "newTargetBps",
        type: "uint16",
      },
    ],
    name: "ComponentTargetUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "oldWeightBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "newWeightBps",
        type: "uint16",
      },
    ],
    name: "ComponentWeightUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "yieldEnabled",
        type: "bool",
      },
    ],
    name: "ComponentYieldUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "activeComponents",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "allComponents",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "assets",
        type: "address[]",
      },
      {
        internalType: "uint16[]",
        name: "weights",
        type: "uint16[]",
      },
    ],
    name: "applyWeights",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "backingComponents",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "outgoing",
        type: "address",
      },
      {
        internalType: "address",
        name: "incoming",
        type: "address",
      },
    ],
    name: "cancelPendingSubstitution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "outgoing",
        type: "address",
      },
      {
        internalType: "address",
        name: "incoming",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "incomingWeightBps",
        type: "uint16",
      },
    ],
    name: "completeSubstitution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "componentAt",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "componentCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "componentHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getComponent",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "uint8",
            name: "decimals",
            type: "uint8",
          },
          {
            internalType: "uint16",
            name: "weightBps",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "targetWeightBps",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "maxDriftBps",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "harvestFeeBps",
            type: "uint16",
          },
          {
            internalType: "uint96",
            name: "maxBalance",
            type: "uint96",
          },
          {
            internalType: "enum ComponentStatus",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "redeemable",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "yieldEnabled",
            type: "bool",
          },
          {
            internalType: "uint40",
            name: "listedAt",
            type: "uint40",
          },
          {
            internalType: "uint40",
            name: "updatedAt",
            type: "uint40",
          },
        ],
        internalType: "struct ComponentConfig",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "isActive",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "isBackingComponent",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "isInKindRedeemable",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "isListed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "decimals_",
        type: "uint8",
      },
      {
        internalType: "uint16",
        name: "weightBps",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "maxDriftBps",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "harvestFeeBps",
        type: "uint16",
      },
      {
        internalType: "uint96",
        name: "maxBalance",
        type: "uint96",
      },
      {
        internalType: "bool",
        name: "yieldEnabled",
        type: "bool",
      },
    ],
    name: "listComponent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "targetWeightBps",
        type: "uint16",
      },
    ],
    name: "markPendingAdd",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "markPendingRemoval",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "redeemableComponents",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "maxDriftBps",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "harvestFeeBps",
        type: "uint16",
      },
      {
        internalType: "uint96",
        name: "maxBalance",
        type: "uint96",
      },
    ],
    name: "setComponentRisk",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "bool",
        name: "redeemable",
        type: "bool",
      },
    ],
    name: "setRedeemable",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "assets",
        type: "address[]",
      },
      {
        internalType: "uint16[]",
        name: "targetWeights",
        type: "uint16[]",
      },
    ],
    name: "setTargetWeights",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "bool",
        name: "enabled",
        type: "bool",
      },
    ],
    name: "setYieldEnabled",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IComponentRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IComponentRegistryInterface {
    return new Interface(_abi) as IComponentRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IComponentRegistry {
    return new Contract(address, _abi, runner) as unknown as IComponentRegistry;
  }
}
