/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReverieOracle,
  IReverieOracleInterface,
} from "../../interfaces/IReverieOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "priceIsFresh",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "priceTimestamp",
    outputs: [
      {
        internalType: "uint40",
        name: "",
        type: "uint40",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IReverieOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IReverieOracleInterface {
    return new Interface(_abi) as IReverieOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IReverieOracle {
    return new Contract(address, _abi, runner) as unknown as IReverieOracle;
  }
}
