/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReverieBasketProtocol,
  IReverieBasketProtocolInterface,
} from "../../interfaces/IReverieBasketProtocol";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "source",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "grossAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feeAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "netAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "reportHash",
        type: "bytes32",
      },
    ],
    name: "Harvested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "supplyBasis",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "components",
        type: "uint256",
      },
    ],
    name: "InKindRedeemed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "components",
        type: "uint256",
      },
    ],
    name: "Minted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "ProtocolPaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "ProtocolUnpaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "components",
        type: "uint256",
      },
    ],
    name: "Redeemed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "RetiredAssetSwept",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint64",
        name: "nonce",
        type: "uint64",
      },
      {
        indexed: true,
        internalType: "address",
        name: "outgoing",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "incoming",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "incomingWeightBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint40",
        name: "executableAt",
        type: "uint40",
      },
      {
        indexed: false,
        internalType: "uint40",
        name: "expiresAt",
        type: "uint40",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "memoHash",
        type: "bytes32",
      },
    ],
    name: "SubstitutionAnnounced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint64",
        name: "nonce",
        type: "uint64",
      },
      {
        indexed: true,
        internalType: "address",
        name: "outgoing",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "incoming",
        type: "address",
      },
    ],
    name: "SubstitutionCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint64",
        name: "nonce",
        type: "uint64",
      },
      {
        indexed: true,
        internalType: "address",
        name: "outgoing",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "incoming",
        type: "address",
      },
    ],
    name: "SubstitutionCompleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint64",
        name: "nonce",
        type: "uint64",
      },
      {
        indexed: true,
        internalType: "address",
        name: "incoming",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "source",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "SubstitutionInventoryReceived",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oldTreasury",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newTreasury",
        type: "address",
      },
    ],
    name: "TreasuryUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint64",
        name: "nonce",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint40",
        name: "executableAt",
        type: "uint40",
      },
      {
        indexed: false,
        internalType: "uint40",
        name: "expiresAt",
        type: "uint40",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "componentHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "memoHash",
        type: "bytes32",
      },
    ],
    name: "WeightUpdateAnnounced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint64",
        name: "nonce",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "componentHash",
        type: "bytes32",
      },
    ],
    name: "WeightUpdateApplied",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint64",
        name: "nonce",
        type: "uint64",
      },
    ],
    name: "WeightUpdateCancelled",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "accountSnapshot",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "account",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "shares",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "grossClaimValue",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "accountingClaimValue",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "address",
                name: "asset",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct AssetAmount[]",
            name: "activeClaims",
            type: "tuple[]",
          },
        ],
        internalType: "struct AccountSnapshot",
        name: "snapshot",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "accountingBasketValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "accountingNavPerShare",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "outgoing",
        type: "address",
      },
      {
        internalType: "address",
        name: "incoming",
        type: "address",
      },
      {
        internalType: "uint40",
        name: "delaySeconds",
        type: "uint40",
      },
      {
        internalType: "uint40",
        name: "ttlSeconds",
        type: "uint40",
      },
      {
        internalType: "bytes32",
        name: "memoHash",
        type: "bytes32",
      },
    ],
    name: "announceSubstitution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "assets",
        type: "address[]",
      },
      {
        internalType: "uint16[]",
        name: "targetWeights",
        type: "uint16[]",
      },
      {
        internalType: "uint40",
        name: "delaySeconds",
        type: "uint40",
      },
      {
        internalType: "uint40",
        name: "ttlSeconds",
        type: "uint40",
      },
      {
        internalType: "bytes32",
        name: "memoHash",
        type: "bytes32",
      },
    ],
    name: "announceWeightUpdate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "applyWeightUpdate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "backedSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "cancelSubstitution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "cancelWeightUpdate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "completeSubstitution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "componentValue",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "balance",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "price",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "uint16",
            name: "weightBps",
            type: "uint16",
          },
          {
            internalType: "enum ComponentStatus",
            name: "status",
            type: "uint8",
          },
        ],
        internalType: "struct ComponentValue",
        name: "value",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "assets",
        type: "address[]",
      },
    ],
    name: "componentValues",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "balance",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "price",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "uint16",
            name: "weightBps",
            type: "uint16",
          },
          {
            internalType: "enum ComponentStatus",
            name: "status",
            type: "uint8",
          },
        ],
        internalType: "struct ComponentValue[]",
        name: "values",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentSubstitution",
    outputs: [
      {
        components: [
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "enum ScheduleState",
            name: "state",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "outgoing",
            type: "address",
          },
          {
            internalType: "address",
            name: "incoming",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "outgoingWeightBps",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "incomingWeightBps",
            type: "uint16",
          },
          {
            internalType: "uint40",
            name: "announcedAt",
            type: "uint40",
          },
          {
            internalType: "uint40",
            name: "executableAt",
            type: "uint40",
          },
          {
            internalType: "uint40",
            name: "expiresAt",
            type: "uint40",
          },
          {
            internalType: "uint256",
            name: "outgoingBalanceSnapshot",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "incomingRequiredValue",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "incomingReceived",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "memoHash",
            type: "bytes32",
          },
        ],
        internalType: "struct SubstitutionPlan",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentWeightUpdate",
    outputs: [
      {
        components: [
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "enum ScheduleState",
            name: "state",
            type: "uint8",
          },
          {
            internalType: "uint40",
            name: "announcedAt",
            type: "uint40",
          },
          {
            internalType: "uint40",
            name: "executableAt",
            type: "uint40",
          },
          {
            internalType: "uint40",
            name: "expiresAt",
            type: "uint40",
          },
          {
            internalType: "bytes32",
            name: "componentHash",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "memoHash",
            type: "bytes32",
          },
        ],
        internalType: "struct WeightUpdate",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "grossBasketValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "source",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "reportHash",
        type: "bytes32",
      },
    ],
    name: "harvest",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "address",
            name: "source",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "grossAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "netAmount",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "reportHash",
            type: "bytes32",
          },
          {
            internalType: "uint40",
            name: "timestamp",
            type: "uint40",
          },
        ],
        internalType: "struct HarvestReport",
        name: "report",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "lastHarvest",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "address",
            name: "source",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "grossAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "netAmount",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "reportHash",
            type: "bytes32",
          },
          {
            internalType: "uint40",
            name: "timestamp",
            type: "uint40",
          },
        ],
        internalType: "struct HarvestReport",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lastSubstitution",
    outputs: [
      {
        components: [
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "enum ScheduleState",
            name: "state",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "outgoing",
            type: "address",
          },
          {
            internalType: "address",
            name: "incoming",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "outgoingWeightBps",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "incomingWeightBps",
            type: "uint16",
          },
          {
            internalType: "uint40",
            name: "announcedAt",
            type: "uint40",
          },
          {
            internalType: "uint40",
            name: "executableAt",
            type: "uint40",
          },
          {
            internalType: "uint40",
            name: "expiresAt",
            type: "uint40",
          },
          {
            internalType: "uint256",
            name: "outgoingBalanceSnapshot",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "incomingRequiredValue",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "incomingReceived",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "memoHash",
            type: "bytes32",
          },
        ],
        internalType: "struct SubstitutionPlan",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "basketAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "minted",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "navPerShare",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "navReport",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "totalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "grossValue",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "accountingValue",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "backedSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "navPerShare",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "accountingNavPerShare",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "transitionWindow",
            type: "bool",
          },
        ],
        internalType: "struct NavReport",
        name: "report",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingWeightAssets",
    outputs: [
      {
        internalType: "address[]",
        name: "assets",
        type: "address[]",
      },
      {
        internalType: "uint16[]",
        name: "weights",
        type: "uint16[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "requestedAssets",
        type: "address[]",
      },
    ],
    name: "previewInKindRedeem",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "shares",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "supplyBasis",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "selectedLane",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "transitionWindow",
            type: "bool",
          },
          {
            components: [
              {
                internalType: "address",
                name: "asset",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct AssetAmount[]",
            name: "outputs",
            type: "tuple[]",
          },
        ],
        internalType: "struct RedeemQuote",
        name: "quote",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "basketAmount",
        type: "uint256",
      },
    ],
    name: "previewMint",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "basketAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "grossValue",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "address",
                name: "asset",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct AssetAmount[]",
            name: "deposits",
            type: "tuple[]",
          },
        ],
        internalType: "struct MintQuote",
        name: "quote",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    name: "previewRedeem",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "shares",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "supplyBasis",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "selectedLane",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "transitionWindow",
            type: "bool",
          },
          {
            components: [
              {
                internalType: "address",
                name: "asset",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct AssetAmount[]",
            name: "outputs",
            type: "tuple[]",
          },
        ],
        internalType: "struct RedeemQuote",
        name: "quote",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "source",
        type: "address",
      },
    ],
    name: "receiveSubstitutionInventory",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "redeem",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
        ],
        internalType: "struct AssetAmount[]",
        name: "outputs",
        type: "tuple[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "requestedAssets",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "redeemInKind",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
        ],
        internalType: "struct AssetAmount[]",
        name: "outputs",
        type: "tuple[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newTreasury",
        type: "address",
      },
    ],
    name: "setTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "sweepRetiredAsset",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "token",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "treasury",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReverieBasketProtocol__factory {
  static readonly abi = _abi;
  static createInterface(): IReverieBasketProtocolInterface {
    return new Interface(_abi) as IReverieBasketProtocolInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IReverieBasketProtocol {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IReverieBasketProtocol;
  }
}
