/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ReveriePriceOracle {
  export type PriceRecordStruct = {
    price: BigNumberish;
    minPrice: BigNumberish;
    maxPrice: BigNumberish;
    updatedAt: BigNumberish;
    heartbeat: BigNumberish;
    enabled: boolean;
  };

  export type PriceRecordStructOutput = [
    price: bigint,
    minPrice: bigint,
    maxPrice: bigint,
    updatedAt: bigint,
    heartbeat: bigint,
    enabled: boolean
  ] & {
    price: bigint;
    minPrice: bigint;
    maxPrice: bigint;
    updatedAt: bigint;
    heartbeat: bigint;
    enabled: boolean;
  };
}

export interface ReveriePriceOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "GOVERNOR_ROLE"
      | "GUARDIAN_ROLE"
      | "KEEPER_ROLE"
      | "PAUSER_ROLE"
      | "REBALANCER_ROLE"
      | "RISK_MANAGER_ROLE"
      | "STRATEGIST_ROLE"
      | "assetAt"
      | "assetCount"
      | "configureAsset"
      | "disableAsset"
      | "getPrice"
      | "grantRole"
      | "hasRole"
      | "heartbeat"
      | "priceBounds"
      | "priceIsFresh"
      | "priceTimestamp"
      | "recordOf"
      | "renounceRole"
      | "revokeRole"
      | "setPrice"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PriceConfigured"
      | "PriceDisabled"
      | "PriceUpdated"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GUARDIAN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEEPER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REBALANCER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RISK_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STRATEGIST_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assetCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "configureAsset",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disableAsset",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "heartbeat",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "priceBounds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "priceIsFresh",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "priceTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrice",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GUARDIAN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KEEPER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REBALANCER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RISK_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STRATEGIST_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assetAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assetCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "configureAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "heartbeat", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceBounds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceIsFresh",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recordOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPrice", data: BytesLike): Result;
}

export namespace PriceConfiguredEvent {
  export type InputTuple = [
    asset: AddressLike,
    minPrice: BigNumberish,
    maxPrice: BigNumberish,
    heartbeat: BigNumberish
  ];
  export type OutputTuple = [
    asset: string,
    minPrice: bigint,
    maxPrice: bigint,
    heartbeat: bigint
  ];
  export interface OutputObject {
    asset: string;
    minPrice: bigint;
    maxPrice: bigint;
    heartbeat: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceDisabledEvent {
  export type InputTuple = [asset: AddressLike];
  export type OutputTuple = [asset: string];
  export interface OutputObject {
    asset: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [
    asset: AddressLike,
    oldPrice: BigNumberish,
    newPrice: BigNumberish,
    updatedAt: BigNumberish
  ];
  export type OutputTuple = [
    asset: string,
    oldPrice: bigint,
    newPrice: bigint,
    updatedAt: bigint
  ];
  export interface OutputObject {
    asset: string;
    oldPrice: bigint;
    newPrice: bigint;
    updatedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReveriePriceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): ReveriePriceOracle;
  waitForDeployment(): Promise<this>;

  interface: ReveriePriceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GOVERNOR_ROLE: TypedContractMethod<[], [string], "view">;

  GUARDIAN_ROLE: TypedContractMethod<[], [string], "view">;

  KEEPER_ROLE: TypedContractMethod<[], [string], "view">;

  PAUSER_ROLE: TypedContractMethod<[], [string], "view">;

  REBALANCER_ROLE: TypedContractMethod<[], [string], "view">;

  RISK_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  STRATEGIST_ROLE: TypedContractMethod<[], [string], "view">;

  assetAt: TypedContractMethod<[index: BigNumberish], [string], "view">;

  assetCount: TypedContractMethod<[], [bigint], "view">;

  configureAsset: TypedContractMethod<
    [
      asset: AddressLike,
      minPrice: BigNumberish,
      maxPrice: BigNumberish,
      heartbeat: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  disableAsset: TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;

  getPrice: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  heartbeat: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  priceBounds: TypedContractMethod<
    [asset: AddressLike],
    [[bigint, bigint] & { minPrice: bigint; maxPrice: bigint }],
    "view"
  >;

  priceIsFresh: TypedContractMethod<[asset: AddressLike], [boolean], "view">;

  priceTimestamp: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  recordOf: TypedContractMethod<
    [asset: AddressLike],
    [ReveriePriceOracle.PriceRecordStructOutput],
    "view"
  >;

  renounceRole: TypedContractMethod<[role: BytesLike], [void], "nonpayable">;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setPrice: TypedContractMethod<
    [asset: AddressLike, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GOVERNOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GUARDIAN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEEPER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PAUSER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REBALANCER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RISK_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "STRATEGIST_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "assetAt"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "assetCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "configureAsset"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      minPrice: BigNumberish,
      maxPrice: BigNumberish,
      heartbeat: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disableAsset"
  ): TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "heartbeat"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "priceBounds"
  ): TypedContractMethod<
    [asset: AddressLike],
    [[bigint, bigint] & { minPrice: bigint; maxPrice: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "priceIsFresh"
  ): TypedContractMethod<[asset: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "priceTimestamp"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordOf"
  ): TypedContractMethod<
    [asset: AddressLike],
    [ReveriePriceOracle.PriceRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<[role: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPrice"
  ): TypedContractMethod<
    [asset: AddressLike, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PriceConfigured"
  ): TypedContractEvent<
    PriceConfiguredEvent.InputTuple,
    PriceConfiguredEvent.OutputTuple,
    PriceConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "PriceDisabled"
  ): TypedContractEvent<
    PriceDisabledEvent.InputTuple,
    PriceDisabledEvent.OutputTuple,
    PriceDisabledEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "PriceConfigured(address,uint256,uint256,uint40)": TypedContractEvent<
      PriceConfiguredEvent.InputTuple,
      PriceConfiguredEvent.OutputTuple,
      PriceConfiguredEvent.OutputObject
    >;
    PriceConfigured: TypedContractEvent<
      PriceConfiguredEvent.InputTuple,
      PriceConfiguredEvent.OutputTuple,
      PriceConfiguredEvent.OutputObject
    >;

    "PriceDisabled(address)": TypedContractEvent<
      PriceDisabledEvent.InputTuple,
      PriceDisabledEvent.OutputTuple,
      PriceDisabledEvent.OutputObject
    >;
    PriceDisabled: TypedContractEvent<
      PriceDisabledEvent.InputTuple,
      PriceDisabledEvent.OutputTuple,
      PriceDisabledEvent.OutputObject
    >;

    "PriceUpdated(address,uint256,uint256,uint40)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
