/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ReverieFeeLedger {
  export type FeeBucketStruct = {
    accrued: BigNumberish;
    claimed: BigNumberish;
    reserved: BigNumberish;
    lastAccruedAt: BigNumberish;
    lastClaimedAt: BigNumberish;
  };

  export type FeeBucketStructOutput = [
    accrued: bigint,
    claimed: bigint,
    reserved: bigint,
    lastAccruedAt: bigint,
    lastClaimedAt: bigint
  ] & {
    accrued: bigint;
    claimed: bigint;
    reserved: bigint;
    lastAccruedAt: bigint;
    lastClaimedAt: bigint;
  };

  export type FeeRouteStruct = {
    receiver: AddressLike;
    shareBps: BigNumberish;
    enabled: boolean;
  };

  export type FeeRouteStructOutput = [
    receiver: string,
    shareBps: bigint,
    enabled: boolean
  ] & { receiver: string; shareBps: bigint; enabled: boolean };
}

export interface ReverieFeeLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS"
      | "DEFAULT_ADMIN_ROLE"
      | "GOVERNOR_ROLE"
      | "GUARDIAN_ROLE"
      | "KEEPER_ROLE"
      | "PAUSER_ROLE"
      | "REBALANCER_ROLE"
      | "RISK_MANAGER_ROLE"
      | "STRATEGIST_ROLE"
      | "accrue"
      | "bucketOf"
      | "claim"
      | "claimable"
      | "clearRoutes"
      | "grantRole"
      | "hasRole"
      | "release"
      | "renounceRole"
      | "reserve"
      | "revokeRole"
      | "routeAt"
      | "routeCount"
      | "routesOf"
      | "setRouteEnabled"
      | "setRoutes"
      | "trackedAssets"
      | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeesAccrued"
      | "FeesClaimed"
      | "FeesReleased"
      | "FeesReserved"
      | "RoleGranted"
      | "RoleRevoked"
      | "RouteSet"
      | "RoutesCleared"
  ): EventFragment;

  encodeFunctionData(functionFragment: "BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GUARDIAN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEEPER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REBALANCER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RISK_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STRATEGIST_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accrue",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bucketOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "claimable",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "clearRoutes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reserve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "routeAt",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "routeCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "routesOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRouteEnabled",
    values: [AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRoutes",
    values: [AddressLike, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "trackedAssets",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(functionFragment: "BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GUARDIAN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KEEPER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REBALANCER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RISK_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STRATEGIST_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "accrue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bucketOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "clearRoutes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reserve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "routeAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "routeCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "routesOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRouteEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRoutes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "trackedAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace FeesAccruedEvent {
  export type InputTuple = [
    asset: AddressLike,
    amount: BigNumberish,
    reason: BytesLike
  ];
  export type OutputTuple = [asset: string, amount: bigint, reason: string];
  export interface OutputObject {
    asset: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesClaimedEvent {
  export type InputTuple = [
    asset: AddressLike,
    receiver: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [asset: string, receiver: string, amount: bigint];
  export interface OutputObject {
    asset: string;
    receiver: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesReleasedEvent {
  export type InputTuple = [asset: AddressLike, amount: BigNumberish];
  export type OutputTuple = [asset: string, amount: bigint];
  export interface OutputObject {
    asset: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesReservedEvent {
  export type InputTuple = [asset: AddressLike, amount: BigNumberish];
  export type OutputTuple = [asset: string, amount: bigint];
  export interface OutputObject {
    asset: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteSetEvent {
  export type InputTuple = [
    asset: AddressLike,
    index: BigNumberish,
    receiver: AddressLike,
    shareBps: BigNumberish,
    enabled: boolean
  ];
  export type OutputTuple = [
    asset: string,
    index: bigint,
    receiver: string,
    shareBps: bigint,
    enabled: boolean
  ];
  export interface OutputObject {
    asset: string;
    index: bigint;
    receiver: string;
    shareBps: bigint;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoutesClearedEvent {
  export type InputTuple = [asset: AddressLike];
  export type OutputTuple = [asset: string];
  export interface OutputObject {
    asset: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReverieFeeLedger extends BaseContract {
  connect(runner?: ContractRunner | null): ReverieFeeLedger;
  waitForDeployment(): Promise<this>;

  interface: ReverieFeeLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GOVERNOR_ROLE: TypedContractMethod<[], [string], "view">;

  GUARDIAN_ROLE: TypedContractMethod<[], [string], "view">;

  KEEPER_ROLE: TypedContractMethod<[], [string], "view">;

  PAUSER_ROLE: TypedContractMethod<[], [string], "view">;

  REBALANCER_ROLE: TypedContractMethod<[], [string], "view">;

  RISK_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  STRATEGIST_ROLE: TypedContractMethod<[], [string], "view">;

  accrue: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, reason: BytesLike],
    [void],
    "nonpayable"
  >;

  bucketOf: TypedContractMethod<
    [asset: AddressLike],
    [ReverieFeeLedger.FeeBucketStructOutput],
    "view"
  >;

  claim: TypedContractMethod<[asset: AddressLike], [bigint], "nonpayable">;

  claimable: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  clearRoutes: TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  release: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<[role: BytesLike], [void], "nonpayable">;

  reserve: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  routeAt: TypedContractMethod<
    [asset: AddressLike, index: BigNumberish],
    [ReverieFeeLedger.FeeRouteStructOutput],
    "view"
  >;

  routeCount: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  routesOf: TypedContractMethod<
    [asset: AddressLike],
    [ReverieFeeLedger.FeeRouteStructOutput[]],
    "view"
  >;

  setRouteEnabled: TypedContractMethod<
    [asset: AddressLike, index: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setRoutes: TypedContractMethod<
    [asset: AddressLike, receivers: AddressLike[], shares: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  trackedAssets: TypedContractMethod<[], [string[]], "view">;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GOVERNOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GUARDIAN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEEPER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PAUSER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REBALANCER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RISK_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "STRATEGIST_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "accrue"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, reason: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bucketOf"
  ): TypedContractMethod<
    [asset: AddressLike],
    [ReverieFeeLedger.FeeBucketStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "claimable"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "clearRoutes"
  ): TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<[role: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reserve"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "routeAt"
  ): TypedContractMethod<
    [asset: AddressLike, index: BigNumberish],
    [ReverieFeeLedger.FeeRouteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "routeCount"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "routesOf"
  ): TypedContractMethod<
    [asset: AddressLike],
    [ReverieFeeLedger.FeeRouteStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "setRouteEnabled"
  ): TypedContractMethod<
    [asset: AddressLike, index: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRoutes"
  ): TypedContractMethod<
    [asset: AddressLike, receivers: AddressLike[], shares: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "trackedAssets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FeesAccrued"
  ): TypedContractEvent<
    FeesAccruedEvent.InputTuple,
    FeesAccruedEvent.OutputTuple,
    FeesAccruedEvent.OutputObject
  >;
  getEvent(
    key: "FeesClaimed"
  ): TypedContractEvent<
    FeesClaimedEvent.InputTuple,
    FeesClaimedEvent.OutputTuple,
    FeesClaimedEvent.OutputObject
  >;
  getEvent(
    key: "FeesReleased"
  ): TypedContractEvent<
    FeesReleasedEvent.InputTuple,
    FeesReleasedEvent.OutputTuple,
    FeesReleasedEvent.OutputObject
  >;
  getEvent(
    key: "FeesReserved"
  ): TypedContractEvent<
    FeesReservedEvent.InputTuple,
    FeesReservedEvent.OutputTuple,
    FeesReservedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RouteSet"
  ): TypedContractEvent<
    RouteSetEvent.InputTuple,
    RouteSetEvent.OutputTuple,
    RouteSetEvent.OutputObject
  >;
  getEvent(
    key: "RoutesCleared"
  ): TypedContractEvent<
    RoutesClearedEvent.InputTuple,
    RoutesClearedEvent.OutputTuple,
    RoutesClearedEvent.OutputObject
  >;

  filters: {
    "FeesAccrued(address,uint256,bytes32)": TypedContractEvent<
      FeesAccruedEvent.InputTuple,
      FeesAccruedEvent.OutputTuple,
      FeesAccruedEvent.OutputObject
    >;
    FeesAccrued: TypedContractEvent<
      FeesAccruedEvent.InputTuple,
      FeesAccruedEvent.OutputTuple,
      FeesAccruedEvent.OutputObject
    >;

    "FeesClaimed(address,address,uint256)": TypedContractEvent<
      FeesClaimedEvent.InputTuple,
      FeesClaimedEvent.OutputTuple,
      FeesClaimedEvent.OutputObject
    >;
    FeesClaimed: TypedContractEvent<
      FeesClaimedEvent.InputTuple,
      FeesClaimedEvent.OutputTuple,
      FeesClaimedEvent.OutputObject
    >;

    "FeesReleased(address,uint256)": TypedContractEvent<
      FeesReleasedEvent.InputTuple,
      FeesReleasedEvent.OutputTuple,
      FeesReleasedEvent.OutputObject
    >;
    FeesReleased: TypedContractEvent<
      FeesReleasedEvent.InputTuple,
      FeesReleasedEvent.OutputTuple,
      FeesReleasedEvent.OutputObject
    >;

    "FeesReserved(address,uint256)": TypedContractEvent<
      FeesReservedEvent.InputTuple,
      FeesReservedEvent.OutputTuple,
      FeesReservedEvent.OutputObject
    >;
    FeesReserved: TypedContractEvent<
      FeesReservedEvent.InputTuple,
      FeesReservedEvent.OutputTuple,
      FeesReservedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "RouteSet(address,uint256,address,uint16,bool)": TypedContractEvent<
      RouteSetEvent.InputTuple,
      RouteSetEvent.OutputTuple,
      RouteSetEvent.OutputObject
    >;
    RouteSet: TypedContractEvent<
      RouteSetEvent.InputTuple,
      RouteSetEvent.OutputTuple,
      RouteSetEvent.OutputObject
    >;

    "RoutesCleared(address)": TypedContractEvent<
      RoutesClearedEvent.InputTuple,
      RoutesClearedEvent.OutputTuple,
      RoutesClearedEvent.OutputObject
    >;
    RoutesCleared: TypedContractEvent<
      RoutesClearedEvent.InputTuple,
      RoutesClearedEvent.OutputTuple,
      RoutesClearedEvent.OutputObject
    >;
  };
}
