/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type PolicySnapshotStruct = {
  maxHarvestFeeBps: BigNumberish;
  maxWeightDriftBps: BigNumberish;
  maxSubstitutionShortfallBps: BigNumberish;
  minWeightDelay: BigNumberish;
  minSubstitutionDelay: BigNumberish;
  maxScheduleTTL: BigNumberish;
  redemptionsPausedDuringSubstitution: boolean;
};

export type PolicySnapshotStructOutput = [
  maxHarvestFeeBps: bigint,
  maxWeightDriftBps: bigint,
  maxSubstitutionShortfallBps: bigint,
  minWeightDelay: bigint,
  minSubstitutionDelay: bigint,
  maxScheduleTTL: bigint,
  redemptionsPausedDuringSubstitution: boolean
] & {
  maxHarvestFeeBps: bigint;
  maxWeightDriftBps: bigint;
  maxSubstitutionShortfallBps: bigint;
  minWeightDelay: bigint;
  minSubstitutionDelay: bigint;
  maxScheduleTTL: bigint;
  redemptionsPausedDuringSubstitution: boolean;
};

export interface ReverieRiskPolicyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "GOVERNOR_ROLE"
      | "GUARDIAN_ROLE"
      | "KEEPER_ROLE"
      | "PAUSER_ROLE"
      | "REBALANCER_ROLE"
      | "RISK_MANAGER_ROLE"
      | "STRATEGIST_ROLE"
      | "grantRole"
      | "hasRole"
      | "maxHarvestFeeBps"
      | "maxScheduleTTL"
      | "maxSubstitutionShortfallBps"
      | "maxWeightDriftBps"
      | "minSubstitutionDelay"
      | "minWeightDelay"
      | "redemptionsPausedDuringSubstitution"
      | "renounceRole"
      | "revokeRole"
      | "setDelayPolicy"
      | "setHarvestFeeLimit"
      | "setSubstitutionRedemptionPolicy"
      | "setSubstitutionShortfallLimit"
      | "setWeightDriftLimit"
      | "snapshot"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DelayPolicyUpdated"
      | "HarvestFeeLimitUpdated"
      | "RoleGranted"
      | "RoleRevoked"
      | "SubstitutionRedemptionPolicyUpdated"
      | "SubstitutionShortfallUpdated"
      | "WeightDriftLimitUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GUARDIAN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEEPER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REBALANCER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RISK_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STRATEGIST_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxHarvestFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxScheduleTTL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxSubstitutionShortfallBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxWeightDriftBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minSubstitutionDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minWeightDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redemptionsPausedDuringSubstitution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDelayPolicy",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHarvestFeeLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSubstitutionRedemptionPolicy",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSubstitutionShortfallLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWeightDriftLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "snapshot", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GUARDIAN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KEEPER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REBALANCER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RISK_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STRATEGIST_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxHarvestFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxScheduleTTL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxSubstitutionShortfallBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxWeightDriftBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minSubstitutionDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minWeightDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redemptionsPausedDuringSubstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDelayPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHarvestFeeLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSubstitutionRedemptionPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSubstitutionShortfallLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWeightDriftLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "snapshot", data: BytesLike): Result;
}

export namespace DelayPolicyUpdatedEvent {
  export type InputTuple = [
    minWeightDelay: BigNumberish,
    minSubstitutionDelay: BigNumberish,
    maxScheduleTTL: BigNumberish
  ];
  export type OutputTuple = [
    minWeightDelay: bigint,
    minSubstitutionDelay: bigint,
    maxScheduleTTL: bigint
  ];
  export interface OutputObject {
    minWeightDelay: bigint;
    minSubstitutionDelay: bigint;
    maxScheduleTTL: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HarvestFeeLimitUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubstitutionRedemptionPolicyUpdatedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubstitutionShortfallUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WeightDriftLimitUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReverieRiskPolicy extends BaseContract {
  connect(runner?: ContractRunner | null): ReverieRiskPolicy;
  waitForDeployment(): Promise<this>;

  interface: ReverieRiskPolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GOVERNOR_ROLE: TypedContractMethod<[], [string], "view">;

  GUARDIAN_ROLE: TypedContractMethod<[], [string], "view">;

  KEEPER_ROLE: TypedContractMethod<[], [string], "view">;

  PAUSER_ROLE: TypedContractMethod<[], [string], "view">;

  REBALANCER_ROLE: TypedContractMethod<[], [string], "view">;

  RISK_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  STRATEGIST_ROLE: TypedContractMethod<[], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  maxHarvestFeeBps: TypedContractMethod<[], [bigint], "view">;

  maxScheduleTTL: TypedContractMethod<[], [bigint], "view">;

  maxSubstitutionShortfallBps: TypedContractMethod<[], [bigint], "view">;

  maxWeightDriftBps: TypedContractMethod<[], [bigint], "view">;

  minSubstitutionDelay: TypedContractMethod<[], [bigint], "view">;

  minWeightDelay: TypedContractMethod<[], [bigint], "view">;

  redemptionsPausedDuringSubstitution: TypedContractMethod<
    [],
    [boolean],
    "view"
  >;

  renounceRole: TypedContractMethod<[role: BytesLike], [void], "nonpayable">;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setDelayPolicy: TypedContractMethod<
    [
      newMinWeightDelay: BigNumberish,
      newMinSubstitutionDelay: BigNumberish,
      newMaxScheduleTTL: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setHarvestFeeLimit: TypedContractMethod<
    [newLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSubstitutionRedemptionPolicy: TypedContractMethod<
    [paused: boolean],
    [void],
    "nonpayable"
  >;

  setSubstitutionShortfallLimit: TypedContractMethod<
    [newLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setWeightDriftLimit: TypedContractMethod<
    [newLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  snapshot: TypedContractMethod<[], [PolicySnapshotStructOutput], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GOVERNOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GUARDIAN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEEPER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PAUSER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REBALANCER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RISK_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "STRATEGIST_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxHarvestFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxScheduleTTL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxSubstitutionShortfallBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxWeightDriftBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minSubstitutionDelay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minWeightDelay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "redemptionsPausedDuringSubstitution"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<[role: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDelayPolicy"
  ): TypedContractMethod<
    [
      newMinWeightDelay: BigNumberish,
      newMinSubstitutionDelay: BigNumberish,
      newMaxScheduleTTL: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setHarvestFeeLimit"
  ): TypedContractMethod<[newLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSubstitutionRedemptionPolicy"
  ): TypedContractMethod<[paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSubstitutionShortfallLimit"
  ): TypedContractMethod<[newLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWeightDriftLimit"
  ): TypedContractMethod<[newLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "snapshot"
  ): TypedContractMethod<[], [PolicySnapshotStructOutput], "view">;

  getEvent(
    key: "DelayPolicyUpdated"
  ): TypedContractEvent<
    DelayPolicyUpdatedEvent.InputTuple,
    DelayPolicyUpdatedEvent.OutputTuple,
    DelayPolicyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HarvestFeeLimitUpdated"
  ): TypedContractEvent<
    HarvestFeeLimitUpdatedEvent.InputTuple,
    HarvestFeeLimitUpdatedEvent.OutputTuple,
    HarvestFeeLimitUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SubstitutionRedemptionPolicyUpdated"
  ): TypedContractEvent<
    SubstitutionRedemptionPolicyUpdatedEvent.InputTuple,
    SubstitutionRedemptionPolicyUpdatedEvent.OutputTuple,
    SubstitutionRedemptionPolicyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SubstitutionShortfallUpdated"
  ): TypedContractEvent<
    SubstitutionShortfallUpdatedEvent.InputTuple,
    SubstitutionShortfallUpdatedEvent.OutputTuple,
    SubstitutionShortfallUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WeightDriftLimitUpdated"
  ): TypedContractEvent<
    WeightDriftLimitUpdatedEvent.InputTuple,
    WeightDriftLimitUpdatedEvent.OutputTuple,
    WeightDriftLimitUpdatedEvent.OutputObject
  >;

  filters: {
    "DelayPolicyUpdated(uint40,uint40,uint40)": TypedContractEvent<
      DelayPolicyUpdatedEvent.InputTuple,
      DelayPolicyUpdatedEvent.OutputTuple,
      DelayPolicyUpdatedEvent.OutputObject
    >;
    DelayPolicyUpdated: TypedContractEvent<
      DelayPolicyUpdatedEvent.InputTuple,
      DelayPolicyUpdatedEvent.OutputTuple,
      DelayPolicyUpdatedEvent.OutputObject
    >;

    "HarvestFeeLimitUpdated(uint16,uint16)": TypedContractEvent<
      HarvestFeeLimitUpdatedEvent.InputTuple,
      HarvestFeeLimitUpdatedEvent.OutputTuple,
      HarvestFeeLimitUpdatedEvent.OutputObject
    >;
    HarvestFeeLimitUpdated: TypedContractEvent<
      HarvestFeeLimitUpdatedEvent.InputTuple,
      HarvestFeeLimitUpdatedEvent.OutputTuple,
      HarvestFeeLimitUpdatedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SubstitutionRedemptionPolicyUpdated(bool)": TypedContractEvent<
      SubstitutionRedemptionPolicyUpdatedEvent.InputTuple,
      SubstitutionRedemptionPolicyUpdatedEvent.OutputTuple,
      SubstitutionRedemptionPolicyUpdatedEvent.OutputObject
    >;
    SubstitutionRedemptionPolicyUpdated: TypedContractEvent<
      SubstitutionRedemptionPolicyUpdatedEvent.InputTuple,
      SubstitutionRedemptionPolicyUpdatedEvent.OutputTuple,
      SubstitutionRedemptionPolicyUpdatedEvent.OutputObject
    >;

    "SubstitutionShortfallUpdated(uint16,uint16)": TypedContractEvent<
      SubstitutionShortfallUpdatedEvent.InputTuple,
      SubstitutionShortfallUpdatedEvent.OutputTuple,
      SubstitutionShortfallUpdatedEvent.OutputObject
    >;
    SubstitutionShortfallUpdated: TypedContractEvent<
      SubstitutionShortfallUpdatedEvent.InputTuple,
      SubstitutionShortfallUpdatedEvent.OutputTuple,
      SubstitutionShortfallUpdatedEvent.OutputObject
    >;

    "WeightDriftLimitUpdated(uint16,uint16)": TypedContractEvent<
      WeightDriftLimitUpdatedEvent.InputTuple,
      WeightDriftLimitUpdatedEvent.OutputTuple,
      WeightDriftLimitUpdatedEvent.OutputObject
    >;
    WeightDriftLimitUpdated: TypedContractEvent<
      WeightDriftLimitUpdatedEvent.InputTuple,
      WeightDriftLimitUpdatedEvent.OutputTuple,
      WeightDriftLimitUpdatedEvent.OutputObject
    >;
  };
}
