/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ReverieBufferedYieldAdapter {
  export type StrategyPositionStruct = {
    principal: BigNumberish;
    realizedYield: BigNumberish;
    loss: BigNumberish;
    reservedLiquidity: BigNumberish;
    lastReportAt: BigNumberish;
    enabled: boolean;
  };

  export type StrategyPositionStructOutput = [
    principal: bigint,
    realizedYield: bigint,
    loss: bigint,
    reservedLiquidity: bigint,
    lastReportAt: bigint,
    enabled: boolean
  ] & {
    principal: bigint;
    realizedYield: bigint;
    loss: bigint;
    reservedLiquidity: bigint;
    lastReportAt: bigint;
    enabled: boolean;
  };
}

export interface ReverieBufferedYieldAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "GOVERNOR_ROLE"
      | "GUARDIAN_ROLE"
      | "KEEPER_ROLE"
      | "PAUSER_ROLE"
      | "REBALANCER_ROLE"
      | "RISK_MANAGER_ROLE"
      | "STRATEGIST_ROLE"
      | "deposit"
      | "disableAsset"
      | "enableAsset"
      | "grantRole"
      | "hasRole"
      | "liquidAssets"
      | "managedAssets"
      | "positionOf"
      | "releaseLiquidity"
      | "renounceRole"
      | "reportLoss"
      | "reportYield"
      | "reserveLiquidity"
      | "revokeRole"
      | "totalAssets"
      | "vault"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "LiquidityReleased"
      | "LiquidityReserved"
      | "LossReported"
      | "RoleGranted"
      | "RoleRevoked"
      | "StrategyAssetDisabled"
      | "StrategyAssetEnabled"
      | "Withdrawn"
      | "YieldReported"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GUARDIAN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEEPER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REBALANCER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RISK_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STRATEGIST_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disableAsset",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "enableAsset",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidAssets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "managedAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "positionOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseLiquidity",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reportLoss",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reportYield",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reserveLiquidity",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAssets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GUARDIAN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KEEPER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REBALANCER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RISK_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STRATEGIST_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disableAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "managedAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "positionOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reportLoss", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reportYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [asset: AddressLike, amount: BigNumberish];
  export type OutputTuple = [asset: string, amount: bigint];
  export interface OutputObject {
    asset: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityReleasedEvent {
  export type InputTuple = [asset: AddressLike, amount: BigNumberish];
  export type OutputTuple = [asset: string, amount: bigint];
  export interface OutputObject {
    asset: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityReservedEvent {
  export type InputTuple = [asset: AddressLike, amount: BigNumberish];
  export type OutputTuple = [asset: string, amount: bigint];
  export interface OutputObject {
    asset: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LossReportedEvent {
  export type InputTuple = [
    asset: AddressLike,
    amount: BigNumberish,
    reportHash: BytesLike
  ];
  export type OutputTuple = [asset: string, amount: bigint, reportHash: string];
  export interface OutputObject {
    asset: string;
    amount: bigint;
    reportHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyAssetDisabledEvent {
  export type InputTuple = [asset: AddressLike];
  export type OutputTuple = [asset: string];
  export interface OutputObject {
    asset: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyAssetEnabledEvent {
  export type InputTuple = [asset: AddressLike];
  export type OutputTuple = [asset: string];
  export interface OutputObject {
    asset: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    asset: AddressLike,
    receiver: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [asset: string, receiver: string, amount: bigint];
  export interface OutputObject {
    asset: string;
    receiver: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldReportedEvent {
  export type InputTuple = [
    asset: AddressLike,
    amount: BigNumberish,
    reportHash: BytesLike
  ];
  export type OutputTuple = [asset: string, amount: bigint, reportHash: string];
  export interface OutputObject {
    asset: string;
    amount: bigint;
    reportHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReverieBufferedYieldAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): ReverieBufferedYieldAdapter;
  waitForDeployment(): Promise<this>;

  interface: ReverieBufferedYieldAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GOVERNOR_ROLE: TypedContractMethod<[], [string], "view">;

  GUARDIAN_ROLE: TypedContractMethod<[], [string], "view">;

  KEEPER_ROLE: TypedContractMethod<[], [string], "view">;

  PAUSER_ROLE: TypedContractMethod<[], [string], "view">;

  REBALANCER_ROLE: TypedContractMethod<[], [string], "view">;

  RISK_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  STRATEGIST_ROLE: TypedContractMethod<[], [string], "view">;

  deposit: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  disableAsset: TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;

  enableAsset: TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  liquidAssets: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  managedAssets: TypedContractMethod<[], [string[]], "view">;

  positionOf: TypedContractMethod<
    [asset: AddressLike],
    [ReverieBufferedYieldAdapter.StrategyPositionStructOutput],
    "view"
  >;

  releaseLiquidity: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<[role: BytesLike], [void], "nonpayable">;

  reportLoss: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, reportHash: BytesLike],
    [void],
    "nonpayable"
  >;

  reportYield: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, reportHash: BytesLike],
    [void],
    "nonpayable"
  >;

  reserveLiquidity: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  totalAssets: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  vault: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, receiver: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GOVERNOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GUARDIAN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEEPER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PAUSER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REBALANCER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RISK_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "STRATEGIST_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disableAsset"
  ): TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "enableAsset"
  ): TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "liquidAssets"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "managedAssets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "positionOf"
  ): TypedContractMethod<
    [asset: AddressLike],
    [ReverieBufferedYieldAdapter.StrategyPositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "releaseLiquidity"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<[role: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reportLoss"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, reportHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reportYield"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, reportHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reserveLiquidity"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalAssets"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, receiver: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityReleased"
  ): TypedContractEvent<
    LiquidityReleasedEvent.InputTuple,
    LiquidityReleasedEvent.OutputTuple,
    LiquidityReleasedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityReserved"
  ): TypedContractEvent<
    LiquidityReservedEvent.InputTuple,
    LiquidityReservedEvent.OutputTuple,
    LiquidityReservedEvent.OutputObject
  >;
  getEvent(
    key: "LossReported"
  ): TypedContractEvent<
    LossReportedEvent.InputTuple,
    LossReportedEvent.OutputTuple,
    LossReportedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StrategyAssetDisabled"
  ): TypedContractEvent<
    StrategyAssetDisabledEvent.InputTuple,
    StrategyAssetDisabledEvent.OutputTuple,
    StrategyAssetDisabledEvent.OutputObject
  >;
  getEvent(
    key: "StrategyAssetEnabled"
  ): TypedContractEvent<
    StrategyAssetEnabledEvent.InputTuple,
    StrategyAssetEnabledEvent.OutputTuple,
    StrategyAssetEnabledEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "YieldReported"
  ): TypedContractEvent<
    YieldReportedEvent.InputTuple,
    YieldReportedEvent.OutputTuple,
    YieldReportedEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "LiquidityReleased(address,uint256)": TypedContractEvent<
      LiquidityReleasedEvent.InputTuple,
      LiquidityReleasedEvent.OutputTuple,
      LiquidityReleasedEvent.OutputObject
    >;
    LiquidityReleased: TypedContractEvent<
      LiquidityReleasedEvent.InputTuple,
      LiquidityReleasedEvent.OutputTuple,
      LiquidityReleasedEvent.OutputObject
    >;

    "LiquidityReserved(address,uint256)": TypedContractEvent<
      LiquidityReservedEvent.InputTuple,
      LiquidityReservedEvent.OutputTuple,
      LiquidityReservedEvent.OutputObject
    >;
    LiquidityReserved: TypedContractEvent<
      LiquidityReservedEvent.InputTuple,
      LiquidityReservedEvent.OutputTuple,
      LiquidityReservedEvent.OutputObject
    >;

    "LossReported(address,uint256,bytes32)": TypedContractEvent<
      LossReportedEvent.InputTuple,
      LossReportedEvent.OutputTuple,
      LossReportedEvent.OutputObject
    >;
    LossReported: TypedContractEvent<
      LossReportedEvent.InputTuple,
      LossReportedEvent.OutputTuple,
      LossReportedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "StrategyAssetDisabled(address)": TypedContractEvent<
      StrategyAssetDisabledEvent.InputTuple,
      StrategyAssetDisabledEvent.OutputTuple,
      StrategyAssetDisabledEvent.OutputObject
    >;
    StrategyAssetDisabled: TypedContractEvent<
      StrategyAssetDisabledEvent.InputTuple,
      StrategyAssetDisabledEvent.OutputTuple,
      StrategyAssetDisabledEvent.OutputObject
    >;

    "StrategyAssetEnabled(address)": TypedContractEvent<
      StrategyAssetEnabledEvent.InputTuple,
      StrategyAssetEnabledEvent.OutputTuple,
      StrategyAssetEnabledEvent.OutputObject
    >;
    StrategyAssetEnabled: TypedContractEvent<
      StrategyAssetEnabledEvent.InputTuple,
      StrategyAssetEnabledEvent.OutputTuple,
      StrategyAssetEnabledEvent.OutputObject
    >;

    "Withdrawn(address,address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;

    "YieldReported(address,uint256,bytes32)": TypedContractEvent<
      YieldReportedEvent.InputTuple,
      YieldReportedEvent.OutputTuple,
      YieldReportedEvent.OutputObject
    >;
    YieldReported: TypedContractEvent<
      YieldReportedEvent.InputTuple,
      YieldReportedEvent.OutputTuple,
      YieldReportedEvent.OutputObject
    >;
  };
}
