/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type ComponentValueStruct = {
  asset: AddressLike;
  balance: BigNumberish;
  price: BigNumberish;
  value: BigNumberish;
  weightBps: BigNumberish;
  status: BigNumberish;
};

export type ComponentValueStructOutput = [
  asset: string,
  balance: bigint,
  price: bigint,
  value: bigint,
  weightBps: bigint,
  status: bigint
] & {
  asset: string;
  balance: bigint;
  price: bigint;
  value: bigint;
  weightBps: bigint;
  status: bigint;
};

export type ComponentConfigStruct = {
  asset: AddressLike;
  decimals: BigNumberish;
  weightBps: BigNumberish;
  targetWeightBps: BigNumberish;
  maxDriftBps: BigNumberish;
  harvestFeeBps: BigNumberish;
  maxBalance: BigNumberish;
  status: BigNumberish;
  redeemable: boolean;
  yieldEnabled: boolean;
  listedAt: BigNumberish;
  updatedAt: BigNumberish;
};

export type ComponentConfigStructOutput = [
  asset: string,
  decimals: bigint,
  weightBps: bigint,
  targetWeightBps: bigint,
  maxDriftBps: bigint,
  harvestFeeBps: bigint,
  maxBalance: bigint,
  status: bigint,
  redeemable: boolean,
  yieldEnabled: boolean,
  listedAt: bigint,
  updatedAt: bigint
] & {
  asset: string;
  decimals: bigint;
  weightBps: bigint;
  targetWeightBps: bigint;
  maxDriftBps: bigint;
  harvestFeeBps: bigint;
  maxBalance: bigint;
  status: bigint;
  redeemable: boolean;
  yieldEnabled: boolean;
  listedAt: bigint;
  updatedAt: bigint;
};

export type NavReportStruct = {
  totalSupply: BigNumberish;
  grossValue: BigNumberish;
  accountingValue: BigNumberish;
  backedSupply: BigNumberish;
  navPerShare: BigNumberish;
  accountingNavPerShare: BigNumberish;
  transitionWindow: boolean;
};

export type NavReportStructOutput = [
  totalSupply: bigint,
  grossValue: bigint,
  accountingValue: bigint,
  backedSupply: bigint,
  navPerShare: bigint,
  accountingNavPerShare: bigint,
  transitionWindow: boolean
] & {
  totalSupply: bigint;
  grossValue: bigint;
  accountingValue: bigint;
  backedSupply: bigint;
  navPerShare: bigint;
  accountingNavPerShare: bigint;
  transitionWindow: boolean;
};

export type WeightUpdateStruct = {
  nonce: BigNumberish;
  state: BigNumberish;
  announcedAt: BigNumberish;
  executableAt: BigNumberish;
  expiresAt: BigNumberish;
  componentHash: BytesLike;
  memoHash: BytesLike;
};

export type WeightUpdateStructOutput = [
  nonce: bigint,
  state: bigint,
  announcedAt: bigint,
  executableAt: bigint,
  expiresAt: bigint,
  componentHash: string,
  memoHash: string
] & {
  nonce: bigint;
  state: bigint;
  announcedAt: bigint;
  executableAt: bigint;
  expiresAt: bigint;
  componentHash: string;
  memoHash: string;
};

export type SubstitutionPlanStruct = {
  nonce: BigNumberish;
  state: BigNumberish;
  outgoing: AddressLike;
  incoming: AddressLike;
  outgoingWeightBps: BigNumberish;
  incomingWeightBps: BigNumberish;
  announcedAt: BigNumberish;
  executableAt: BigNumberish;
  expiresAt: BigNumberish;
  outgoingBalanceSnapshot: BigNumberish;
  incomingRequiredValue: BigNumberish;
  incomingReceived: BigNumberish;
  memoHash: BytesLike;
};

export type SubstitutionPlanStructOutput = [
  nonce: bigint,
  state: bigint,
  outgoing: string,
  incoming: string,
  outgoingWeightBps: bigint,
  incomingWeightBps: bigint,
  announcedAt: bigint,
  executableAt: bigint,
  expiresAt: bigint,
  outgoingBalanceSnapshot: bigint,
  incomingRequiredValue: bigint,
  incomingReceived: bigint,
  memoHash: string
] & {
  nonce: bigint;
  state: bigint;
  outgoing: string;
  incoming: string;
  outgoingWeightBps: bigint;
  incomingWeightBps: bigint;
  announcedAt: bigint;
  executableAt: bigint;
  expiresAt: bigint;
  outgoingBalanceSnapshot: bigint;
  incomingRequiredValue: bigint;
  incomingReceived: bigint;
  memoHash: string;
};

export type AssetAmountStruct = { asset: AddressLike; amount: BigNumberish };

export type AssetAmountStructOutput = [asset: string, amount: bigint] & {
  asset: string;
  amount: bigint;
};

export type MintQuoteStruct = {
  basketAmount: BigNumberish;
  grossValue: BigNumberish;
  deposits: AssetAmountStruct[];
};

export type MintQuoteStructOutput = [
  basketAmount: bigint,
  grossValue: bigint,
  deposits: AssetAmountStructOutput[]
] & {
  basketAmount: bigint;
  grossValue: bigint;
  deposits: AssetAmountStructOutput[];
};

export type RedeemQuoteStruct = {
  shares: BigNumberish;
  supplyBasis: BigNumberish;
  selectedLane: boolean;
  transitionWindow: boolean;
  outputs: AssetAmountStruct[];
};

export type RedeemQuoteStructOutput = [
  shares: bigint,
  supplyBasis: bigint,
  selectedLane: boolean,
  transitionWindow: boolean,
  outputs: AssetAmountStructOutput[]
] & {
  shares: bigint;
  supplyBasis: bigint;
  selectedLane: boolean;
  transitionWindow: boolean;
  outputs: AssetAmountStructOutput[];
};

export interface ReverieLensInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeComponents"
      | "backingComponents"
      | "components"
      | "oracle"
      | "oracleRecords"
      | "overview"
      | "pendingWeights"
      | "protocol"
      | "quoteMint"
      | "quoteRedeem"
      | "quoteSelectedRedeem"
      | "redeemableAssets"
      | "registry"
      | "selectedClaimsForAllRedeemable"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "activeComponents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "backingComponents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "components",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "oracleRecords",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(functionFragment: "overview", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingWeights",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "protocol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quoteMint",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteRedeem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteSelectedRedeem",
    values: [BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemableAssets",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "selectedClaimsForAllRedeemable",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeComponents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "backingComponents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "components", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "oracleRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "overview", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quoteMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quoteRedeem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteSelectedRedeem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemableAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "selectedClaimsForAllRedeemable",
    data: BytesLike
  ): Result;
}

export interface ReverieLens extends BaseContract {
  connect(runner?: ContractRunner | null): ReverieLens;
  waitForDeployment(): Promise<this>;

  interface: ReverieLensInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeComponents: TypedContractMethod<
    [],
    [ComponentValueStructOutput[]],
    "view"
  >;

  backingComponents: TypedContractMethod<
    [],
    [ComponentValueStructOutput[]],
    "view"
  >;

  components: TypedContractMethod<[], [ComponentConfigStructOutput[]], "view">;

  oracle: TypedContractMethod<[], [string], "view">;

  oracleRecords: TypedContractMethod<
    [assets: AddressLike[]],
    [
      [bigint[], bigint[], boolean[]] & {
        prices: bigint[];
        timestamps: bigint[];
        fresh: boolean[];
      }
    ],
    "view"
  >;

  overview: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        boolean,
        NavReportStructOutput,
        WeightUpdateStructOutput,
        SubstitutionPlanStructOutput
      ] & {
        token: string;
        treasury: string;
        paused: boolean;
        report: NavReportStructOutput;
        weightUpdate: WeightUpdateStructOutput;
        substitution: SubstitutionPlanStructOutput;
      }
    ],
    "view"
  >;

  pendingWeights: TypedContractMethod<
    [],
    [[string[], bigint[]] & { assets: string[]; weights: bigint[] }],
    "view"
  >;

  protocol: TypedContractMethod<[], [string], "view">;

  quoteMint: TypedContractMethod<
    [basketAmount: BigNumberish],
    [MintQuoteStructOutput],
    "view"
  >;

  quoteRedeem: TypedContractMethod<
    [shares: BigNumberish],
    [RedeemQuoteStructOutput],
    "view"
  >;

  quoteSelectedRedeem: TypedContractMethod<
    [shares: BigNumberish, assets: AddressLike[]],
    [RedeemQuoteStructOutput],
    "view"
  >;

  redeemableAssets: TypedContractMethod<[], [string[]], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  selectedClaimsForAllRedeemable: TypedContractMethod<
    [shares: BigNumberish],
    [AssetAmountStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeComponents"
  ): TypedContractMethod<[], [ComponentValueStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "backingComponents"
  ): TypedContractMethod<[], [ComponentValueStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "components"
  ): TypedContractMethod<[], [ComponentConfigStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "oracleRecords"
  ): TypedContractMethod<
    [assets: AddressLike[]],
    [
      [bigint[], bigint[], boolean[]] & {
        prices: bigint[];
        timestamps: bigint[];
        fresh: boolean[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "overview"
  ): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        boolean,
        NavReportStructOutput,
        WeightUpdateStructOutput,
        SubstitutionPlanStructOutput
      ] & {
        token: string;
        treasury: string;
        paused: boolean;
        report: NavReportStructOutput;
        weightUpdate: WeightUpdateStructOutput;
        substitution: SubstitutionPlanStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingWeights"
  ): TypedContractMethod<
    [],
    [[string[], bigint[]] & { assets: string[]; weights: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quoteMint"
  ): TypedContractMethod<
    [basketAmount: BigNumberish],
    [MintQuoteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "quoteRedeem"
  ): TypedContractMethod<
    [shares: BigNumberish],
    [RedeemQuoteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "quoteSelectedRedeem"
  ): TypedContractMethod<
    [shares: BigNumberish, assets: AddressLike[]],
    [RedeemQuoteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "redeemableAssets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "selectedClaimsForAllRedeemable"
  ): TypedContractMethod<
    [shares: BigNumberish],
    [AssetAmountStructOutput[]],
    "view"
  >;

  filters: {};
}
