/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  ReverieErrors,
  ReverieErrorsInterface,
} from "../../errors/ReverieErrors";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "balance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "cap",
        type: "uint256",
      },
    ],
    name: "CapExceeded",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "ComponentAlreadyListed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "ComponentNotActive",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "ComponentNotListed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "ComponentNotRedeemable",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "ComponentNotYielding",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "observedBps",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "allowedBps",
        type: "uint256",
      },
    ],
    name: "DriftLimitExceeded",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "DuplicateComponent",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "available",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "required",
        type: "uint256",
      },
    ],
    name: "InsufficientBalance",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidAmount",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidArrayLength",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "InvalidComponent",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "delaySeconds",
        type: "uint256",
      },
    ],
    name: "InvalidDelay",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "feeBps",
        type: "uint256",
      },
    ],
    name: "InvalidFee",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "heartbeat",
        type: "uint256",
      },
    ],
    name: "InvalidHeartbeat",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "state",
        type: "uint8",
      },
    ],
    name: "InvalidScheduleState",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidSigner",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "outgoing",
        type: "address",
      },
      {
        internalType: "address",
        name: "incoming",
        type: "address",
      },
    ],
    name: "InvalidSubstitution",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "weight",
        type: "uint256",
      },
    ],
    name: "InvalidWeight",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "sum",
        type: "uint256",
      },
    ],
    name: "InvalidWeightSum",
    type: "error",
  },
  {
    inputs: [],
    name: "NoActiveSchedule",
    type: "error",
  },
  {
    inputs: [],
    name: "PermitExpired",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "PriceOutOfBounds",
    type: "error",
  },
  {
    inputs: [],
    name: "ProtocolPaused",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
    ],
    name: "RoleAlreadyGranted",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
    ],
    name: "RoleNotGranted",
    type: "error",
  },
  {
    inputs: [],
    name: "SameAsset",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "nonce",
        type: "uint64",
      },
    ],
    name: "ScheduleActive",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "nowTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expiresAt",
        type: "uint256",
      },
    ],
    name: "ScheduleExpired",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "nowTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "executableAt",
        type: "uint256",
      },
    ],
    name: "ScheduleNotExecutable",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "lastUpdated",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "heartbeat",
        type: "uint256",
      },
    ],
    name: "StalePrice",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "available",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "required",
        type: "uint256",
      },
    ],
    name: "SubstitutionInventoryShortfall",
    type: "error",
  },
  {
    inputs: [],
    name: "SupplyUnavailable",
    type: "error",
  },
  {
    inputs: [],
    name: "TransferFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
    ],
    name: "Unauthorized",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddress",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212207ee4de4d3b6deae0b7b7fc0ac0197cf522b2bb8ec63389ee309a003f7c0bba7464736f6c63430008180033";

type ReverieErrorsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReverieErrorsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReverieErrors__factory extends ContractFactory {
  constructor(...args: ReverieErrorsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ReverieErrors & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReverieErrors__factory {
    return super.connect(runner) as ReverieErrors__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReverieErrorsInterface {
    return new Interface(_abi) as ReverieErrorsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReverieErrors {
    return new Contract(address, _abi, runner) as unknown as ReverieErrors;
  }
}
