/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type ComponentConfigStruct = {
  asset: AddressLike;
  decimals: BigNumberish;
  weightBps: BigNumberish;
  targetWeightBps: BigNumberish;
  maxDriftBps: BigNumberish;
  harvestFeeBps: BigNumberish;
  maxBalance: BigNumberish;
  status: BigNumberish;
  redeemable: boolean;
  yieldEnabled: boolean;
  listedAt: BigNumberish;
  updatedAt: BigNumberish;
};

export type ComponentConfigStructOutput = [
  asset: string,
  decimals: bigint,
  weightBps: bigint,
  targetWeightBps: bigint,
  maxDriftBps: bigint,
  harvestFeeBps: bigint,
  maxBalance: bigint,
  status: bigint,
  redeemable: boolean,
  yieldEnabled: boolean,
  listedAt: bigint,
  updatedAt: bigint
] & {
  asset: string;
  decimals: bigint;
  weightBps: bigint;
  targetWeightBps: bigint;
  maxDriftBps: bigint;
  harvestFeeBps: bigint;
  maxBalance: bigint;
  status: bigint;
  redeemable: boolean;
  yieldEnabled: boolean;
  listedAt: bigint;
  updatedAt: bigint;
};

export interface IComponentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeComponents"
      | "allComponents"
      | "applyWeights"
      | "backingComponents"
      | "cancelPendingSubstitution"
      | "completeSubstitution"
      | "componentAt"
      | "componentCount"
      | "componentHash"
      | "getComponent"
      | "isActive"
      | "isBackingComponent"
      | "isInKindRedeemable"
      | "isListed"
      | "listComponent"
      | "markPendingAdd"
      | "markPendingRemoval"
      | "redeemableComponents"
      | "setComponentRisk"
      | "setRedeemable"
      | "setTargetWeights"
      | "setYieldEnabled"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComponentListed"
      | "ComponentRedeemableUpdated"
      | "ComponentRiskUpdated"
      | "ComponentStatusUpdated"
      | "ComponentTargetUpdated"
      | "ComponentWeightUpdated"
      | "ComponentYieldUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeComponents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allComponents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "applyWeights",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "backingComponents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPendingSubstitution",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeSubstitution",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "componentAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "componentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "componentHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getComponent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isActive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBackingComponent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInKindRedeemable",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isListed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listComponent",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "markPendingAdd",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markPendingRemoval",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemableComponents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setComponentRisk",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRedeemable",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTargetWeights",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setYieldEnabled",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeComponents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allComponents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "backingComponents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPendingSubstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeSubstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "componentAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "componentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "componentHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getComponent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isBackingComponent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInKindRedeemable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isListed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listComponent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markPendingAdd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markPendingRemoval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemableComponents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setComponentRisk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRedeemable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTargetWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setYieldEnabled",
    data: BytesLike
  ): Result;
}

export namespace ComponentListedEvent {
  export type InputTuple = [
    asset: AddressLike,
    decimals: BigNumberish,
    weightBps: BigNumberish,
    maxDriftBps: BigNumberish,
    harvestFeeBps: BigNumberish
  ];
  export type OutputTuple = [
    asset: string,
    decimals: bigint,
    weightBps: bigint,
    maxDriftBps: bigint,
    harvestFeeBps: bigint
  ];
  export interface OutputObject {
    asset: string;
    decimals: bigint;
    weightBps: bigint;
    maxDriftBps: bigint;
    harvestFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComponentRedeemableUpdatedEvent {
  export type InputTuple = [asset: AddressLike, redeemable: boolean];
  export type OutputTuple = [asset: string, redeemable: boolean];
  export interface OutputObject {
    asset: string;
    redeemable: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComponentRiskUpdatedEvent {
  export type InputTuple = [
    asset: AddressLike,
    maxDriftBps: BigNumberish,
    harvestFeeBps: BigNumberish,
    maxBalance: BigNumberish
  ];
  export type OutputTuple = [
    asset: string,
    maxDriftBps: bigint,
    harvestFeeBps: bigint,
    maxBalance: bigint
  ];
  export interface OutputObject {
    asset: string;
    maxDriftBps: bigint;
    harvestFeeBps: bigint;
    maxBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComponentStatusUpdatedEvent {
  export type InputTuple = [
    asset: AddressLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    asset: string,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    asset: string;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComponentTargetUpdatedEvent {
  export type InputTuple = [
    asset: AddressLike,
    oldTargetBps: BigNumberish,
    newTargetBps: BigNumberish
  ];
  export type OutputTuple = [
    asset: string,
    oldTargetBps: bigint,
    newTargetBps: bigint
  ];
  export interface OutputObject {
    asset: string;
    oldTargetBps: bigint;
    newTargetBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComponentWeightUpdatedEvent {
  export type InputTuple = [
    asset: AddressLike,
    oldWeightBps: BigNumberish,
    newWeightBps: BigNumberish
  ];
  export type OutputTuple = [
    asset: string,
    oldWeightBps: bigint,
    newWeightBps: bigint
  ];
  export interface OutputObject {
    asset: string;
    oldWeightBps: bigint;
    newWeightBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComponentYieldUpdatedEvent {
  export type InputTuple = [asset: AddressLike, yieldEnabled: boolean];
  export type OutputTuple = [asset: string, yieldEnabled: boolean];
  export interface OutputObject {
    asset: string;
    yieldEnabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IComponentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IComponentRegistry;
  waitForDeployment(): Promise<this>;

  interface: IComponentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeComponents: TypedContractMethod<[], [string[]], "view">;

  allComponents: TypedContractMethod<[], [string[]], "view">;

  applyWeights: TypedContractMethod<
    [assets: AddressLike[], weights: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  backingComponents: TypedContractMethod<[], [string[]], "view">;

  cancelPendingSubstitution: TypedContractMethod<
    [outgoing: AddressLike, incoming: AddressLike],
    [void],
    "nonpayable"
  >;

  completeSubstitution: TypedContractMethod<
    [
      outgoing: AddressLike,
      incoming: AddressLike,
      incomingWeightBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  componentAt: TypedContractMethod<[index: BigNumberish], [string], "view">;

  componentCount: TypedContractMethod<[], [bigint], "view">;

  componentHash: TypedContractMethod<[], [string], "view">;

  getComponent: TypedContractMethod<
    [asset: AddressLike],
    [ComponentConfigStructOutput],
    "view"
  >;

  isActive: TypedContractMethod<[asset: AddressLike], [boolean], "view">;

  isBackingComponent: TypedContractMethod<
    [asset: AddressLike],
    [boolean],
    "view"
  >;

  isInKindRedeemable: TypedContractMethod<
    [asset: AddressLike],
    [boolean],
    "view"
  >;

  isListed: TypedContractMethod<[asset: AddressLike], [boolean], "view">;

  listComponent: TypedContractMethod<
    [
      asset: AddressLike,
      decimals_: BigNumberish,
      weightBps: BigNumberish,
      maxDriftBps: BigNumberish,
      harvestFeeBps: BigNumberish,
      maxBalance: BigNumberish,
      yieldEnabled: boolean
    ],
    [void],
    "nonpayable"
  >;

  markPendingAdd: TypedContractMethod<
    [asset: AddressLike, targetWeightBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  markPendingRemoval: TypedContractMethod<
    [asset: AddressLike],
    [void],
    "nonpayable"
  >;

  redeemableComponents: TypedContractMethod<[], [string[]], "view">;

  setComponentRisk: TypedContractMethod<
    [
      asset: AddressLike,
      maxDriftBps: BigNumberish,
      harvestFeeBps: BigNumberish,
      maxBalance: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setRedeemable: TypedContractMethod<
    [asset: AddressLike, redeemable: boolean],
    [void],
    "nonpayable"
  >;

  setTargetWeights: TypedContractMethod<
    [assets: AddressLike[], targetWeights: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  setYieldEnabled: TypedContractMethod<
    [asset: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeComponents"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "allComponents"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "applyWeights"
  ): TypedContractMethod<
    [assets: AddressLike[], weights: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "backingComponents"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "cancelPendingSubstitution"
  ): TypedContractMethod<
    [outgoing: AddressLike, incoming: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "completeSubstitution"
  ): TypedContractMethod<
    [
      outgoing: AddressLike,
      incoming: AddressLike,
      incomingWeightBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "componentAt"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "componentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "componentHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getComponent"
  ): TypedContractMethod<
    [asset: AddressLike],
    [ComponentConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[asset: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isBackingComponent"
  ): TypedContractMethod<[asset: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isInKindRedeemable"
  ): TypedContractMethod<[asset: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isListed"
  ): TypedContractMethod<[asset: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "listComponent"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      decimals_: BigNumberish,
      weightBps: BigNumberish,
      maxDriftBps: BigNumberish,
      harvestFeeBps: BigNumberish,
      maxBalance: BigNumberish,
      yieldEnabled: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "markPendingAdd"
  ): TypedContractMethod<
    [asset: AddressLike, targetWeightBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "markPendingRemoval"
  ): TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "redeemableComponents"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "setComponentRisk"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      maxDriftBps: BigNumberish,
      harvestFeeBps: BigNumberish,
      maxBalance: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRedeemable"
  ): TypedContractMethod<
    [asset: AddressLike, redeemable: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTargetWeights"
  ): TypedContractMethod<
    [assets: AddressLike[], targetWeights: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setYieldEnabled"
  ): TypedContractMethod<
    [asset: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ComponentListed"
  ): TypedContractEvent<
    ComponentListedEvent.InputTuple,
    ComponentListedEvent.OutputTuple,
    ComponentListedEvent.OutputObject
  >;
  getEvent(
    key: "ComponentRedeemableUpdated"
  ): TypedContractEvent<
    ComponentRedeemableUpdatedEvent.InputTuple,
    ComponentRedeemableUpdatedEvent.OutputTuple,
    ComponentRedeemableUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ComponentRiskUpdated"
  ): TypedContractEvent<
    ComponentRiskUpdatedEvent.InputTuple,
    ComponentRiskUpdatedEvent.OutputTuple,
    ComponentRiskUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ComponentStatusUpdated"
  ): TypedContractEvent<
    ComponentStatusUpdatedEvent.InputTuple,
    ComponentStatusUpdatedEvent.OutputTuple,
    ComponentStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ComponentTargetUpdated"
  ): TypedContractEvent<
    ComponentTargetUpdatedEvent.InputTuple,
    ComponentTargetUpdatedEvent.OutputTuple,
    ComponentTargetUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ComponentWeightUpdated"
  ): TypedContractEvent<
    ComponentWeightUpdatedEvent.InputTuple,
    ComponentWeightUpdatedEvent.OutputTuple,
    ComponentWeightUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ComponentYieldUpdated"
  ): TypedContractEvent<
    ComponentYieldUpdatedEvent.InputTuple,
    ComponentYieldUpdatedEvent.OutputTuple,
    ComponentYieldUpdatedEvent.OutputObject
  >;

  filters: {
    "ComponentListed(address,uint8,uint16,uint16,uint16)": TypedContractEvent<
      ComponentListedEvent.InputTuple,
      ComponentListedEvent.OutputTuple,
      ComponentListedEvent.OutputObject
    >;
    ComponentListed: TypedContractEvent<
      ComponentListedEvent.InputTuple,
      ComponentListedEvent.OutputTuple,
      ComponentListedEvent.OutputObject
    >;

    "ComponentRedeemableUpdated(address,bool)": TypedContractEvent<
      ComponentRedeemableUpdatedEvent.InputTuple,
      ComponentRedeemableUpdatedEvent.OutputTuple,
      ComponentRedeemableUpdatedEvent.OutputObject
    >;
    ComponentRedeemableUpdated: TypedContractEvent<
      ComponentRedeemableUpdatedEvent.InputTuple,
      ComponentRedeemableUpdatedEvent.OutputTuple,
      ComponentRedeemableUpdatedEvent.OutputObject
    >;

    "ComponentRiskUpdated(address,uint16,uint16,uint96)": TypedContractEvent<
      ComponentRiskUpdatedEvent.InputTuple,
      ComponentRiskUpdatedEvent.OutputTuple,
      ComponentRiskUpdatedEvent.OutputObject
    >;
    ComponentRiskUpdated: TypedContractEvent<
      ComponentRiskUpdatedEvent.InputTuple,
      ComponentRiskUpdatedEvent.OutputTuple,
      ComponentRiskUpdatedEvent.OutputObject
    >;

    "ComponentStatusUpdated(address,uint8,uint8)": TypedContractEvent<
      ComponentStatusUpdatedEvent.InputTuple,
      ComponentStatusUpdatedEvent.OutputTuple,
      ComponentStatusUpdatedEvent.OutputObject
    >;
    ComponentStatusUpdated: TypedContractEvent<
      ComponentStatusUpdatedEvent.InputTuple,
      ComponentStatusUpdatedEvent.OutputTuple,
      ComponentStatusUpdatedEvent.OutputObject
    >;

    "ComponentTargetUpdated(address,uint16,uint16)": TypedContractEvent<
      ComponentTargetUpdatedEvent.InputTuple,
      ComponentTargetUpdatedEvent.OutputTuple,
      ComponentTargetUpdatedEvent.OutputObject
    >;
    ComponentTargetUpdated: TypedContractEvent<
      ComponentTargetUpdatedEvent.InputTuple,
      ComponentTargetUpdatedEvent.OutputTuple,
      ComponentTargetUpdatedEvent.OutputObject
    >;

    "ComponentWeightUpdated(address,uint16,uint16)": TypedContractEvent<
      ComponentWeightUpdatedEvent.InputTuple,
      ComponentWeightUpdatedEvent.OutputTuple,
      ComponentWeightUpdatedEvent.OutputObject
    >;
    ComponentWeightUpdated: TypedContractEvent<
      ComponentWeightUpdatedEvent.InputTuple,
      ComponentWeightUpdatedEvent.OutputTuple,
      ComponentWeightUpdatedEvent.OutputObject
    >;

    "ComponentYieldUpdated(address,bool)": TypedContractEvent<
      ComponentYieldUpdatedEvent.InputTuple,
      ComponentYieldUpdatedEvent.OutputTuple,
      ComponentYieldUpdatedEvent.OutputObject
    >;
    ComponentYieldUpdated: TypedContractEvent<
      ComponentYieldUpdatedEvent.InputTuple,
      ComponentYieldUpdatedEvent.OutputTuple,
      ComponentYieldUpdatedEvent.OutputObject
    >;
  };
}
